language_dict = {
    "en": "english",
    "ru": "russian",
    "es": "spanish",
    "pl": "polish",
    "pt": "portuguese",
    "fr": "french",
    "id": "indonesian",
    "el": "greek",
    "de": "german",
    "tr": "turkish",
    "hu": "hungarian",
    "uk": "ukrainian",
    "it": "italian",
    "ro": "romanian",
    "bg": "bulgarian",
    "fi": "finnish",
    "et": "estonian",
    "lt": "lithuanian",
    "lv": "latvian",
    "nl": "dutch",
    "cs": "czech",
    "da": "danish",
    "ja": "japanese",
    "nb": "norwegian",
    "sk": "slovak",
    "sl": "slovenian",
    "sv": "swedish",
    "az": "azerbaijani",
    "kk": "kazakh",
    "ar": "arabic",
    "uz": "uzbek"
}

english,russian,spanish,polish,portuguese,french,indonesian,greek,german,turkish,hungarian,ukrainian,italian,romanian,bulgarian,finnish,estonian,lithuanian,latvian,dutch,czech,danish,japanese,norwegian,slovak,slovenian,swedish,azerbaijani,kazakh,arabic,uzbek