country_to_domain = {
    "United States": "us",
    "United Kingdom": "uk",
    "Canada": "ca",
    "Australia": "au",
    "Germany": "de",
    "France": "fr",
    "Russia": "ru",
    "China": "cn",
    "India": "in",
    "Japan": "jp",
    "Brazil": "br",
    "South Africa": "za",
    "Ukraine": "ua",
    "Italy": "it",
    "Spain": "es",
    "Netherlands": "nl",
    "Switzerland": "ch",
    "Sweden": "se",
    "Norway": "no",
    "Finland": "fi",
    "Denmark": "dk",
    "Belgium": "be",
    "Austria": "at",
    "Poland": "pl",
    "Mexico": "mx",
    "Argentina": "ar",
    "New Zealand": "nz",
    "Ireland": "ie",
    "Greece": "gr",
    "Portugal": "pt",
    "Czech Republic": "cz",
    "Hungary": "hu",
    "Romania": "ro",
    "Israel": "il",
    "South Korea": "kr",
    "Malaysia": "my",
    "Singapore": "sg",
    "Thailand": "th",
    "Philippines": "ph",
    "Vietnam": "vn",
    "Turkey": "tr",
    "Saudi Arabia": "sa",
    "United Arab Emirates": "ae",
    "Qatar": "qa",
    "Kuwait": "kw",
    "Egypt": "eg",
    "Nigeria": "ng",
    "Kenya": "ke",
    "Chile": "cl",
    "Colombia": "co",
    "Peru": "pe",
    "Venezuela": "ve",
    "Ecuador": "ec",
    "Luxembourg": "lu",
    "Slovakia": "sk",
    "Bulgaria": "bg",
    "Croatia": "hr",
    "Slovenia": "si",
    "Estonia": "ee",
    "Latvia": "lv",
    "Lithuania": "lt",
    "Iceland": "is",
    "Malta": "mt",
    "Cyprus": "cy",
    "Indonesia": "id",
    "Pakistan": "pk",
    "Bangladesh": "bd",
    "Nepal": "np",
    "Sri Lanka": "lk",
    "Kazakhstan": "kz",
    "Uzbekistan": "uz",
    "Turkmenistan": "tm",
    "Kyrgyzstan": "kg",
    "Tajikistan": "tj",
    "Georgia": "ge",
    "Armenia": "am",
    "Azerbaijan": "az",
    "Belarus": "by",
    "Moldova": "md",
    "Albania": "al",
    "Macedonia": "mk",
    "Serbia": "rs",
    "Montenegro": "me",
    "Bosnia and Herzegovina": "ba",
    "Costa Rica": "cr",
    "Guatemala": "gt",
    "Honduras": "hn",
    "El Salvador": "sv",
    "Nicaragua": "ni",
    "Panama": "pa",
    "Uruguay": "uy",
    "Paraguay": "py",
    "Jamaica": "jm",
    "Trinidad and Tobago": "tt",
    "Barbados": "bb",
    "Bahamas": "bs",
    "Dominican Republic": "do",
    "Haiti": "ht",
    "Cuba": "cu",
    "Ghana": "gh",
    "Senegal": "sn",
    "Ivory Coast": "ci",
    "Mali": "ml",
    "Niger": "ne",
    "Burkina Faso": "bf",
    "Morocco": "ma",
    "Algeria": "dz",
    "Tunisia": "tn",
    "Libya": "ly",
    "Sudan": "sd",
    "Ethiopia": "et",
    "Somalia": "so",
    "Zimbabwe": "zw",
    "Zambia": "zm",
    "Namibia": "na",
    "Mozambique": "mz",
    "Madagascar": "mg",
    "Angola": "ao",
    "Botswana": "bw",
    "Mauritius": "mu",
    "Fiji": "fj",
    "Papua New Guinea": "pg",
    "Tonga": "to",
    "Samoa": "ws",
    "Vanuatu": "vu",
    "Micronesia": "fm",
    "Palau": "pw",
    "Marshall Islands": "mh",
    "Maldives": "mv",
    "Bahrain": "bh",
    "Oman": "om",
    "Yemen": "ye",
    "Iraq": "iq",
    "Syria": "sy",
    "Lebanon": "lb",
    "Jordan": "jo",
    "Afghanistan": "af",
    "Cambodia": "kh",
    "Laos": "la",
    "Mongolia": "mn",
    "Nauru": "nr",
    "Myanmar": "mm",
    "Andorra": "ad",
    "Antigua and Barbuda": "ag",
    "Dominica": "dm",
    "Grenada": "gd",
    "Saint Kitts and Nevis": "kn",
    "Saint Vincent and the Grenadines": "vc",
    "Saint Lucia": "lc",
    "San Marino": "sm",
    "Liechtenstein": "li",
    "Monaco": "mc",
    "Malawi": "mw",
    "Lesotho": "ls",
    "Swaziland": "sz",
    "Djibouti": "dj",
    "Eritrea": "er",
    "Comoros": "km",
    "Cape Verde": "cv",
    "Seychelles": "sc",
    "Kiribati": "ki",
    "Tuvalu": "tv",
    "Solomon Islands": "sb",
    "Saint Vincent and the Grenadines": "vc",
    "Saint Helena, Ascension and Tristan da Cunha": "sh",
    "Falkland Islands": "fk",
    "Svalbard and Jan Mayen": "sj",
    "Norfolk Island": "nf",
    "Christmas Island": "cx",
    "Pitcairn": "pn",
    "South Georgia and the South Sandwich Islands": "gs",
    "Montenegro": "me",
    "Guernsey": "gg",
    "Isle of Man": "im",
    "Jersey": "je",
    "Aland Islands": "ax",
    "Faroe Islands": "fo",
    "Gibraltar": "gi",
    "Greenland": "gl",
    "Guam": "gu",
    "American Samoa": "as",
    "Cook Islands": "ck",
    "Guadeloupe": "gp",
    "Martinique": "mq",
    "New Caledonia": "nc",
    "French Polynesia": "pf",
    "Mayotte": "yt",
    "Reunion": "re",
    "Saint Pierre and Miquelon": "pm",
    "Wallis and Futuna": "wf",
    "French Southern and Antarctic Lands": "tf",
    "Northern Mariana Islands": "mp",
    "Puerto Rico": "pr",
    "Bouvet Island": "bv",
    "Heard Island and McDonald Islands": "hm",
    "British Indian Ocean Territory": "io",
    "Cocos (Keeling) Islands": "cc",
    "Vatican City": "va",
    "Palestinian territories": "ps",
    "Western Sahara": "eh",
    "East Timor": "tl"
}
