"""
    Напиши 10 идей  на Английском языке, составленных комментариев с подстановкой темы статьи и ключевого слова {game DSA}. 
    Например:f"I just got through with {title_url}, and wow, it's as gripping as playing {key_game}. 
    The future is now, and both these things prove it!". Коментарии должны быть длинной от 350 до 400 символов на игровую тематику, 
    и на простом человеческом языке с использованием структуры реальных коментарии с Reddit. Используй ключевое слово перед указанием 
    темы статьи. Конечный результат запиши в переменну в виде f строк как например comments_prompt = 
    [f"I just got through with {title_url}, and wow, it's as gripping as playing {key_game}]

    Дополни список comments_prompt 20 шаблонами комментариев  с подстановкой темы {title_url} и ключевого слова {key_game}. 
    Коментарии должны быть длинной от 350 до 400 символов на игровую тематику, и на простом человеческом языке с использованием 
    структуры и текста с реальных коментарии с Reddit. Используй ключевое слово перед указанием темы статьи. 
"""
comments_prompt = [
    "I just got through with {title_url}, and wow, it's as gripping as playing {key_game}. The future is now, and both these things prove it!",
    "After reading {title_url}, I'm awestruck. Kinda like the first time I played {key_game}. Both are super innovative and open up a whole new world of possibilities",
    "Diving into {title_url} felt like a journey back in time. Kind of like when I revisit old levels in {key_game}. It's fascinating how much we've progressed!",
    "The article on {title_url} was as eye-opening as the plot twists in {key_game}. Both are so full of surprises, it's impossible to predict what's coming next",
    "Reading {title_url} was like playing a level of {key_game} that's tough but rewarding. Both require focus and critical thinking, and boy do they keep you on your toes!",
    "Going through {title_url} was as thrilling as winning a tough round of {key_game}. Both are breakthroughs in their own right and it's exciting to see them unfold",
    "The article {title_url} was as much of an adventure as a marathon session of {key_game}. The mysteries, the challenges – they both just draw you in!",
    "Reading about {title_url} got my brain buzzing, much like the strategic gameplay in {key_game}. Both are thought-provoking and make you look at things from a whole new perspective",
    "{title_url} was an enlightening read. It's like {key_game} in the way it changes your outlook. They both make you think deeper and question the status quo",
    "Engaging with {title_url} gave me a sense of thrill akin to when I'm playing {key_game}. Both require strategy, a keen mind, and quick decision-making. It's an adrenaline rush!",
    "{title_url} was such an engrossing read! It's like the joy I feel when I'm playing my favorite game, {key_game}. It's a great way to engage and learn new things, just like in the game!",
    "I just had to share how much I enjoyed reading {title_url}. It made me think about the strategies and decisions I make in {key_game}, just as much as it made me ponder the future of VR",
    "Reading about {title_url} made me remember the excitement I had when I first played {key_game}. The thrill and competition - both are so addictive!",
    "{title_url} is as fascinating as each level in {key_game}. The ever-changing landscapes and challenges keep me coming back for more!",
    "I just got through with {title_url}, it felt just like mining for resources in {key_game} - intriguing and full of surprises",
    "I found {title_url} as enlightening as understanding the mechanics of {key_game}. Both require an open mind and a willingness to adapt to new situations",
    "I'm as drawn to {title_url} as I am to playing {key_game}. Both are complex yet fascinating, offering endless opportunities to learn and grow",
    "Reading about {title_url}, I couldn't help but reminisce about the immersive universe of {key_game}. Both provide a refreshing escape from reality",
    "Just like the satisfying achievement of a hard-fought victory in {key_game}, the exploration of {title_url} left me feeling accomplished, having gained new insights",
    "The in-depth analysis in {title_url} kept me as engaged as the intricate strategies required in {key_game}. It's amazing how technology changes our perspective, be it business or gaming!",
    "Just like a nail-biting match in {key_game}, I found the article {title_url} equally exhilarating. It's fascinating to see how the game strategies can be related to real life scenarios",
    "While playing {key_game}, I stumbled upon the article {title_url}. The similarity between the game's strategy and the article's insight left me intrigued. Both are so immersive and enlightening",
    "I found the article {title_url} as engrossing as the gameplay in {key_game}. Both require critical thinking and strategy. It's truly fascinating to see the correlation",
    "The thrill of playing {key_game} is only paralleled by the insight I gained from the article {title_url}. It's amazing how gaming can be as educational as a well-researched article",
    "While playing {key_game}, I often find myself applying strategies I learned from articles like {title_url}. The parallels between gaming and real-life scenarios are astounding",
    "I find the tactical aspect of {key_game} quite similar to the strategic insights from {title_url}. Both make me think and analyze before making decisions",
    "The compelling strategies of {key_game} often remind me of the depth and complexity of articles like {title_url}. The more I delve into both, the more I learn",
    "Immersed in {key_game}, I often see myself applying the insights I got from the article {title_url}. The similarities in strategic planning are quite astounding",
    "The thought process in {key_game} and the insights from {title_url} are surprisingly similar. Both involve thinking ahead and adapting to new challenges",
    "The strategizing I do while playing {key_game} is complemented by the insights I get from articles like {title_url}. It's a perfect blend of entertainment and learning",
    "The immersive storytelling in {key_game} echoes in the thoughtful commentary in {title_url}. Both capture the imagination in such unexpected ways!",
    "Just like how {key_game} revolutionized gameplay, the perspectives in {title_url} are nothing short of groundbreaking. Both are game-changers in their own right!",
    "Stumbling upon {title_url} was as exhilarating as finding a secret level in {key_game}. Each offers a thrilling journey into the unknown",
    "Just like the innovative mechanics in {key_game}, the insights in {title_url} break the mould. Each is a testament to how far we've come!",
    "The plot twists in {key_game} are as unpredictable as the future scenarios outlined in {title_url}. Both keep you guessing at every turn!",
    "Engaging with {title_url} reminded me of the long nights spent strategizing in {key_game}. Both are intellectually stimulating and endlessly fascinating",
    "The way {key_game} pulls you into its world is paralleled by the immersive narratives in {title_url}. Both are captivating experiences that you won't forget anytime soon!",
    "As with the dynamic gameplay of {key_game}, the innovative ideas in {title_url} never cease to amaze me. Both are reminders of the power of creativity",
    "The challenges in {key_game} are as thought-provoking as the discussions in {title_url}. Both push boundaries and encourage critical thinking",
    "Exploring the narratives in {title_url} feels just like delving into the rich lore of {key_game}. Both are mind-expanding experiences that transport you to another world",
    "The expert gameplay in {key_game} is as rewarding as the deep dive into the subjects of {title_url}. Each provides a wealth of knowledge and experiences",
    "Just as every level of {key_game} brings a new challenge, each section of {title_url} offers fresh insights. Both are immersive experiences that leave you wanting more",
    "Engaging with {title_url} was as gripping as the toughest battles in {key_game}. Each requires your full attention, and you won't want to miss a single moment",
    "Just as {key_game} offers an escape from reality, {title_url} opens up a whole new perspective. Both offer a journey into unexplored territories",
    "The intricate strategies of {key_game} are as complex and rewarding as the insights shared in {title_url}. Each gives you a new perspective and challenges your thinking",
    "Just like mastering a level in {key_game}, digesting the knowledge in {title_url} feels like a personal achievement. Both are about overcoming challenges and coming out wiser",
    "The sense of discovery in {key_game} is matched by the unveiling of insights in {title_url}. Both journeys, though different, lead to an unforgettable payoff",
    "Reading {title_url} was like unlocking a new skill in {key_game}. Both experiences are enlightening and open up a plethora of possibilities",
    "Just like {key_game}, the ideas expressed in {title_url} require reflection and strategy. Both are intellectual pursuits that reward the curious mind",
    "Navigating through the perspectives in {title_url} felt like mastering a new strategy in {key_game}. Both require patience and understanding, but the reward is well worth the effort",
    "As a {key_game} fan, the piece on {title_url} resonated deeply with me. It feels like a parallel journey of discovery, just like uncovering easter eggs in the game!",
    "Just as how each boss battle in {key_game} leaves me on edge, so does every revelation in {title_url}. It's a mix of anticipation, excitement and a little bit of fear of the unknown.",
    "Each chapter of {title_url} unfolds like a well-played game of {key_game}. There's a rhythm to it - build, confront, overcome, and repeat. It's as engaging as it gets.",
    "Reading {title_url} feels like a boss fight in {key_game}. Both require careful strategies, patience, and an element of surprise. It's thrilling to see the parallels.",
    "Engaging with {title_url} gave me the same sense of achievement as clearing a particularly tough level in {key_game}. Both are challenging but incredibly rewarding.",
    "Every line of {title_url} held my attention, much like how each moment in {key_game} requires my utmost focus. It's this balance of challenge and engagement that makes both so enjoyable.",
    "Much like the unexpected plot twists in {key_game}, {title_url} kept me on my toes. It's amazing how a game and an article can trigger the same excitement and curiosity.",
    "The level of depth in {title_url} is much like the detailed lore of {key_game}. The more you delve into them, the more you're rewarded with rich knowledge and insights.",
    "Playing {key_game} always leaves me inspired, much like reading {title_url}. Both provide a wealth of ideas and provoke thought, making each interaction a learning experience.",
    "Just as each level in {key_game} is an adventure, so is every section in {title_url}. It's fascinating how both keep me engaged and eager to discover what lies ahead.",
    "The way {key_game} encourages strategic thinking is mirrored in {title_url}. Both challenge assumptions and demand critical thinking, making every interaction a stimulating experience.",
    "As a regular {key_game} player, I find the thought process required in {title_url} quite similar. Both provide a challenging environment that encourages learning and adaptation.",
    "Reading {title_url} and playing {key_game} feels surprisingly similar. Both take me on a journey, challenging my perceptions and leaving me with new perspectives.",
    "Just as {key_game} is an epic journey of discovery, so is {title_url}. Both are engaging narratives filled with unexpected twists and turns. It's hard to put either down!",
    "Playing {key_game} and diving into {title_url} are both journeys of discovery. Each is an exploration of new frontiers, full of thrilling challenges and incredible rewards.",
    "I find the strategic element in {key_game} as thought-provoking as the narratives in {title_url}. Both provide complex, layered experiences that keep me engaged for hours.",
    "The excitement of a co-op mission in {key_game} is mirrored in the teamwork discussed in {title_url}. Both emphasize the importance of coordination and effective communication.",
    "Much like each level in {key_game} brings new challenges, so does each section in {title_url}. Both are well-crafted journeys that push the boundaries of what's possible.",
    "The competitive spirit of {key_game} is reflected in the drive and determination in {title_url}. It's interesting how a game and an article can evoke similar feelings.",
    "When I immerse myself in {key_game}, I'm reminded of the depth and storytelling of {title_url}. Both have an essence that captures the imagination.",
    "The emotion I feel while navigating {key_game} parallels the deep connection I have with {title_url}. They both are masterpieces in their own right.",
    "The drama and intensity of {key_game} mirror the intricate tales woven into {title_url}. Engaging in either is like taking a deep dive into captivating storytelling.",
    "Journeying through {key_game} and reading {title_url} feels like a cinematic experience. Each has its moments that take my breath away.",
    "There's a certain magic in {key_game} that I find echoed in the pages of {title_url}. Both have an allure that's hard to resist.",
    "The worlds of {key_game} and {title_url} are filled with adventure and suspense. Engaging with them is like watching a blockbuster unfold.",
    "I've experienced many tales, but the narrative in {key_game} and the storytelling in {title_url} are unparalleled. They're the kind of epics that stay with you.",
    "There's a rhythm in {key_game} that harmonizes perfectly with the narrative beats of {title_url}. Both evoke powerful emotions.",
    "The passion I see in {key_game} mirrors the heartfelt stories in {title_url}. Both resonate deeply and inspire the soul.",
    "Every challenge in {key_game} and each narrative twist in {title_url} keep me on the edge of my seat. It's an exhilarating ride from start to finish.",
    "The depth of {key_game} and the rich texture of {title_url} remind me of classic films. They both have a timeless appeal.",
    "The way {key_game} unfolds is as mesmerizing as the story arcs in {title_url}. I'm always eager to see what comes next.",
    "I've been transported to many worlds, but {key_game} and {title_url} offer experiences that are both unique and unforgettable.",
    "The essence of {key_game} and the heart of {title_url} intertwine in a dance of narrative brilliance. They're both works of art.",
    "There's an elegance in the gameplay of {key_game} that matches the sophisticated narratives of {title_url}. Both are a testament to the power of storytelling.",
    "Both {key_game} and {title_url} transport me to realms where imagination and reality blur beautifully.",
    "I'm always amazed at how {key_game} and {title_url} can evoke such intense feelings. It's a testament to their craft.",
    "The intricacies of {key_game} paired with the detailed layers of {title_url} are what epic tales are made of.",
    "From the first moment in {key_game} to the captivating narratives in {title_url}, it's clear that both are nothing short of masterpieces.",
    "The world-building in {key_game} is as vast and detailed as the stories spun in {title_url}. It's a treat to dive into both.",
    "Every time I think I've seen it all, {key_game} and {title_url} prove that there are still stories that can surprise and inspire me.",
    "It's rare to find experiences as authentic and moving as {key_game} and {title_url}. They're truly in a league of their own.",
    "I've always believed in the power of stories, and both {key_game} and {title_url} reaffirm that belief with every twist and turn.",
    "Navigating through {key_game} feels like an adventure, much like unraveling the mysteries in {title_url}. Both are journeys worth taking.",
    "It's hard to describe the magic of {key_game}, but it's the same feeling I get when I dive deep into {title_url}. Pure wonder.",
    "There's something timeless about {key_game}, a sentiment that's echoed perfectly in the narratives of {title_url}.",
    "I often lose track of time in {key_game}, much like how engrossed I get in {title_url}. Both are captivating in their unique ways.",
    "The symphony of emotions in {key_game} harmonizes beautifully with the rich tales in {title_url}. It's an experience like no other.",
    "Between the epic journey of {key_game} and the intriguing tales of {title_url}, there's never a dull moment.",
    "I always appreciate a good narrative, and both {key_game} and {title_url} deliver on that front spectacularly.",
    "The thrill of {key_game} is complemented by the depth and beauty of {title_url}. Both are journeys I'd gladly embark on time and again.",
    "The landscapes of {key_game} and the prose of {title_url} paint pictures that are worth a thousand words. Each frame, each line, is art.",
    "There's a narrative depth in {key_game} that resonates perfectly with the tales told in {title_url}. A pairing made in storytelling heaven.",
    "I've witnessed many stories, but few have the gravitas and allure of {key_game} and {title_url}. They're a testament to the art of storytelling.",
    "The vibrant world of {key_game} and the immersive tales of {title_url} are like two sides of the same coin. Both are masterful in their execution.",
    "The echoes of legendary tales can be heard in both {key_game} and {title_url}. Engaging with them is like stepping into a grand epic.",
    "It's truly a privilege to journey through the narrative brilliance of both {key_game} and {title_url}. They leave an indelible mark.",
    "The passion and depth of {key_game} mirrors the intricate tales weaved into {title_url}. Both represent the pinnacle of storytelling.",
    "The allure of {key_game} coupled with the intricate fabric of {title_url} are reminders of why stories have such a profound impact on us.",
    "Both {key_game} and {title_url} have an uncanny ability to transport one to worlds where every moment is filled with wonder.",
    "The charm of {key_game} and the rich tapestry of {title_url} are testaments to how captivating narratives can be when done right.",
    "In {key_game}, as in {title_url}, we see a masterclass of storytelling. Both are mesmerizing experiences that linger long after they're over.",
    "The dynamism of {key_game} and the profound narratives of {title_url} make them an unforgettable duo. It's hard to find a better pairing.",
    "The tapestry of emotions and adventures in {key_game} feels akin to the mesmerizing journey that {title_url} offers. Both are treasures in their own right.",
    "The beauty of {key_game} and the elegance of {title_url} merge to create experiences that are truly larger than life.",
    "It's fascinating how {key_game} and {title_url} can capture the essence of grand tales and condense them into unforgettable narratives.",
    "Every step in {key_game} and every page of {title_url} is a testament to the power of immersive storytelling. I'm constantly enthralled.",
    "The seamless melding of adventure and profundity in {key_game} is reminiscent of the captivating tales found in {title_url}. It's storytelling at its finest.",
    "There's a resonance in {key_game} that harmonizes with the pulse of {title_url}. It's as if both were crafted from the same narrative fabric.",
    "The artistry in {key_game} and the craftsmanship in {title_url} stand as twin pillars of storytelling excellence.",
    "Every twist in {key_game} and turn in {title_url} serves as a reminder of the magic that stories hold. Both are pure narrative genius."
]