import os
import json
import pymysql


# Завантаження конфігураційного файлу
with open(r'SETTINGS\BigData\configs\config_sql_1win.json') as f:
    config = json.load(f)

# Встановлення з'єднання з базою даних
connect_database = pymysql.connect(**config['config_database'],
                                   port=3306,
                                   cursorclass=pymysql.cursors.DictCursor)


data = {'bg': {'bg-bg': ['bg-BG',
                  'България',
                  'София',
                  'пл. „Независимост“ 1',
                  '1000',
                  'бул. Витоша 20',
                  'b-lgariia']},
 'cs': {'cs-cz': ['cs-CZ',
                  'Česká republika',
                  'Praha',
                  'Hradčanské náměstí 1',
                  '118 00',
                  'Václavské náměstí 20',
                  'ceska-republika']},
 'da': {'da-dk': ['da-DK',
                  'Danmark',
                  'København',
                  'Christiansborg Slotsplads 1',
                  '1218',
                  'Strøget 20',
                  'danmark'],
        'da-fo': ['da-FO',
                  'Færøerne',
                  'Tórshavn',
                  'Vaglið 1',
                  '100',
                  'Niels Finsens gøta 20',
                  'faeroerne'],
        'da-gl': ['da-GL',
                  'Grønland',
                  'Nuuk',
                  'Aqqusinersuaq 1',
                  '3900',
                  'Imaneq 20',
                  'gronland']},
 'de': {'de-at': ['de-AT',
                  'Österreich',
                  'Wien',
                  'Ballhausplatz 1',
                  '1010',
                  'Kärntner Straße 20',
                  'osterreich'],
        'de-ch': ['de-CH',
                  'Schweiz',
                  'Bern',
                  'Bundesplatz 1',
                  '3005',
                  'Bahnhofstrasse 20',
                  'schweiz'],
        'de-de': ['de-DE',
                  'Deutschland',
                  'Berlin',
                  'Platz der Republik 1',
                  '11011',
                  'Kurfürstendamm 20',
                  'deutschland'],
        'de-li': ['de-LI',
                  'Liechtenstein',
                  'Vaduz',
                  'Fürst-Franz-Josef-Straße 1',
                  '9490',
                  'Äulestrasse 20',
                  'liechtenstein']},
 'el': {'el-cy': ['el-CY',
                  'Κύπρος',
                  'Λευκωσία',
                  'Πρεζιδεντικό Μέγαρο 1',
                  '1066',
                  'Λήδρας 20',
                  'kupros'],
        'el-gr': ['el-GR',
                  'Ελλάδα',
                  'Αθήνα',
                  'Σύνταγμα 1',
                  '105 57',
                  'Ερμού 20',
                  'ellada']},
 'en': {'en-ad': ['en-AD',
                  'Andorra',
                  'Andorra la Vella',
                  'Meritxell Avenue 20',
                  'AD500',
                  'Business Center Street 1',
                  'andorra'],
        'en-ae': ['en-AE',
                  'United Arab Emirates',
                  'Abu Dhabi',
                  'Corniche Road 50',
                  '0000',
                  'Sheikh Zayed Road 20',
                  'united-arab-emirates'],
        'en-af': ['en-AF',
                  'Afghanistan',
                  'Kabul',
                  'Central Street 5',
                  '1001',
                  'Business Avenue 3',
                  'afghanistan'],
        'en-ag': ['en-AG',
                  'Antigua and Barbuda',
                  "St. John's",
                  'High Street 11',
                  '0000',
                  'Corporate Blvd 2',
                  'antigua-and-barbuda'],
        'en-al': ['en-AL',
                  'Albania',
                  'Tirana',
                  'Skanderbeg Square 12',
                  '1000',
                  'Main Business St 7',
                  'albania'],
        'en-as': ['en-AS',
                  'American Samoa',
                  'Pago Pago',
                  'Central Avenue 6',
                  '96799',
                  'Island Business Way 5',
                  'american-samoa'],
        'en-au': ['en-AU',
                  'Australia',
                  'Canberra',
                  'Commonwealth Ave 15',
                  '2600',
                  'Sydney Business Park 18',
                  'australia'],
        'en-ba': ['en-BA',
                  'Bosnia and Herzegovina',
                  'Sarajevo',
                  'Marsala Tita 20',
                  '71000',
                  'Business Plaza 3',
                  'bosnia-and-herzegovina'],
        'en-bd': ['en-BD',
                  'Bangladesh',
                  'Dhaka',
                  'Mirpur Road 80',
                  '1205',
                  'Commercial Street 16',
                  'bangladesh'],
        'en-bh': ['en-BH',
                  'Bahrain',
                  'Manama',
                  'King Faisal Highway 10',
                  '317',
                  'Financial Harbour 20',
                  'bahrain'],
        'en-bn': ['en-BN',
                  'Brunei',
                  'Bandar Seri Begawan',
                  'Sultan Omar Ali Saifuddien Rd 7',
                  'BS8711',
                  'Business Park 5',
                  'brunei'],
        'en-bs': ['en-BS',
                  'Bahamas',
                  'Nassau',
                  'Bay Street 20',
                  'N-7148',
                  'Corporate Drive 3',
                  'bahamas'],
        'en-bt': ['en-BT',
                  'Bhutan',
                  'Thimphu',
                  'Norzin Lam 12',
                  '11001',
                  'Commercial Road 2',
                  'bhutan'],
        'en-bw': ['en-BW',
                  'Botswana',
                  'Gaborone',
                  'Queens Road 15',
                  '10100',
                  'High-Tech Park 11',
                  'botswana'],
        'en-bz': ['en-BZ',
                  'Belize',
                  'Belmopan',
                  'Ring Road 2',
                  '0000',
                  'Business Circle 6',
                  'belize'],
        'en-ca': ['en-CA',
                  'Canada',
                  'Ottawa',
                  'Wellington Street 45',
                  'K1A 0A6',
                  'Bay Street 100',
                  'canada-en'],
        'en-cc': ['en-CC',
                  'Cocos Islands',
                  'West Island',
                  'Pulu Keeling Drive 3',
                  '6799',
                  'Business Island Way 1',
                  'cocos-islands'],
        'en-cx': ['en-CX',
                  'Christmas Island',
                  'Flying Fish Cove',
                  'Gaze Road 11',
                  '6798',
                  'Corporate Avenue 4',
                  'christmas-island'],
        'en-dm': ['en-DM',
                  'Dominica',
                  'Roseau',
                  'Great George Street 8',
                  '00152',
                  'Financial Center 4',
                  'dominica'],
        'en-eg': ['en-EG',
                  'Egypt',
                  'Cairo',
                  'Tahrir Square 1',
                  '11511',
                  'Smart Village 12',
                  'egypt'],
        'en-er': ['en-ER',
                  'Eritrea',
                  'Asmara',
                  'Independence Avenue 10',
                  '1234',
                  'Business Park 3',
                  'eritrea'],
        'en-et': ['en-ET',
                  'Ethiopia',
                  'Addis Ababa',
                  'Churchill Road 20',
                  '1000',
                  'Kazanchis 5',
                  'ethiopia'],
        'en-fj': ['en-FJ',
                  'Fiji',
                  'Suva',
                  'Victoria Parade 15',
                  '0001',
                  'Fiji Business Park 2',
                  'fiji'],
        'en-fm': ['en-FM',
                  'Micronesia',
                  'Palikir',
                  'Nanpohnmal 4',
                  '96941',
                  'Corporate Avenue 5',
                  'micronesia'],
        'en-gb': ['en-GB',
                  'United Kingdom',
                  'London',
                  'Whitehall 50',
                  'SW1A 2AS',
                  'Canary Wharf 15',
                  'united-kingdom'],
        'en-gg': ['en-GG',
                  'Guernsey',
                  'Saint Peter Port',
                  'High Street 12',
                  'GY1 2HP',
                  'Business Lane 6',
                  'guernsey'],
        'en-gh': ['en-GH',
                  'Ghana',
                  'Accra',
                  'Oxford Street 25',
                  'GA-010-5374',
                  'Airport City 10',
                  'ghana'],
        'en-gm': ['en-GM',
                  'Gambia',
                  'Banjul',
                  'Independence Drive 3',
                  '12345',
                  'Kairaba Avenue 15',
                  'gambia'],
        'en-gy': ['en-GY',
                  'Guyana',
                  'Georgetown',
                  'Regent Street 7',
                  '41237',
                  'Main Business Plaza 15',
                  'guyana'],
        'en-hr': ['en-HR',
                  'Croatia',
                  'Zagreb',
                  'Ilica Street 50',
                  '10000',
                  'Business Tower 20',
                  'croatia'],
        'en-ie': ['en-IE',
                  'Ireland',
                  'Dublin',
                  "O'Connell Street 20",
                  'D01 F5P2',
                  'Docklands Ave 12',
                  'ireland'],
        'en-in': ['en-IN',
                  'India',
                  'New Delhi',
                  'Rajpath 11',
                  '110001',
                  'Cyber City 55',
                  'india'],
        'en-jm': ['en-JM',
                  'Jamaica',
                  'Kingston',
                  'Knutsford Boulevard 5',
                  '876',
                  'New Kingston 3',
                  'jamaica'],
        'en-jo': ['en-JO',
                  'Jordan',
                  'Amman',
                  'Rainbow Street 21',
                  '11118',
                  'Abdali Boulevard 14',
                  'jordan'],
        'en-ke': ['en-KE',
                  'Kenya',
                  'Nairobi',
                  'Kenyatta Avenue 45',
                  '00100',
                  'Westlands Road 11',
                  'kenya'],
        'en-kh': ['en-KH',
                  'Cambodia',
                  'Phnom Penh',
                  'Preah Sihanouk Blvd 12',
                  '12207',
                  'Mao Tse Tung Blvd 32',
                  'cambodia'],
        'en-ki': ['en-KI',
                  'Kiribati',
                  'South Tarawa',
                  'Main Road 6',
                  'G8101',
                  'Bairiki Square 3',
                  'kiribati'],
        'en-kw': ['en-KW',
                  'Kuwait',
                  'Kuwait City',
                  'Gulf Road 9',
                  '13001',
                  'Financial Street 19',
                  'kuwait'],
        'en-la': ['en-LA',
                  'Laos',
                  'Vientiane',
                  'Lane Xang Avenue 16',
                  '01000',
                  'Kumkha Road 10',
                  'laos'],
        'en-lb': ['en-LB',
                  'Lebanon',
                  'Beirut',
                  'Hamra Street 25',
                  '1103',
                  'Verdun Street 8',
                  'lebanon'],
        'en-lc': ['en-LC',
                  'Saint Lucia',
                  'Castries',
                  'Jeremie Street 19',
                  'LC04 101',
                  'Bridge Street 5',
                  'saint-lucia'],
        'en-lk': ['en-LK',
                  'Sri Lanka',
                  'Colombo',
                  'Galle Road 34',
                  '00100',
                  'World Trade Center 23',
                  'sri-lanka'],
        'en-lr': ['en-LR',
                  'Liberia',
                  'Monrovia',
                  'Broad Street 18',
                  '1000',
                  'Mamba Point 5',
                  'liberia'],
        'en-ls': ['en-LS',
                  'Lesotho',
                  'Maseru',
                  'Kingsway Road 20',
                  '100',
                  'Pioneer Road 12',
                  'lesotho'],
        'en-ly': ['en-LY',
                  'Libya',
                  'Tripoli',
                  'Sharia Fatah 44',
                  '82612',
                  "Martyrs' Square 7",
                  'libya'],
        'en-me': ['en-ME',
                  'Montenegro',
                  'Podgorica',
                  'Bulevar Džordža Vašingtona 55',
                  '81000',
                  'Stanka Dragojevića 7',
                  'montenegro'],
        'en-mh': ['en-MH',
                  'Marshall Islands',
                  'Majuro',
                  'Laura Beach Road 9',
                  '96960',
                  'Long Island Boulevard 6',
                  'marshall-islands'],
        'en-mk': ['en-MK',
                  'North Macedonia',
                  'Skopje',
                  'Pella Square 15',
                  '1000',
                  'Business Avenue 20',
                  'north-macedonia'],
        'en-mm': ['en-MM',
                  'Myanmar (Burma)',
                  'Yangon',
                  'Sule Pagoda Road 35',
                  '11181',
                  'Pyay Road 47',
                  'myanmar-burma'],
        'en-mp': ['en-MP',
                  'Northern Mariana Islands',
                  'Saipan',
                  'Beach Road 11',
                  '96950',
                  'Micro Beach 2',
                  'northern-mariana-islands'],
        'en-mt': ['en-MT',
                  'Malta',
                  'Valletta',
                  'Republic Street 29',
                  'VLT 1116',
                  'Merchant Street 8',
                  'malta'],
        'en-mu': ['en-MU',
                  'Mauritius',
                  'Port Louis',
                  'Royal Street 65',
                  '11328',
                  'Caudan Waterfront 22',
                  'mauritius'],
        'en-mv': ['en-MV',
                  'Maldives',
                  'Malé',
                  'Majeedhee Magu 10',
                  '20026',
                  'Orchid Magu 17',
                  'maldives'],
        'en-mw': ['en-MW',
                  'Malawi',
                  'Lilongwe',
                  'Presidential Way 47',
                  '442',
                  'Chilambula Road 14',
                  'malawi'],
        'en-my': ['en-MY',
                  'Malaysia',
                  'Kuala Lumpur',
                  'Jalan Sultan Hishamuddin 35',
                  '50000',
                  'Bukit Bintang Street 20',
                  'malaysia'],
        'en-na': ['en-NA',
                  'Namibia',
                  'Windhoek',
                  'Independence Avenue 52',
                  '10001',
                  'Robert Mugabe Avenue 28',
                  'namibia'],
        'en-ng': ['en-NG',
                  'Nigeria',
                  'Abuja',
                  'Yakubu Gowon Crescent 70',
                  '900001',
                  'Adetokunbo Ademola Crescent 15',
                  'nigeria'],
        'en-np': ['en-NP',
                  'Nepal',
                  'Kathmandu',
                  'Durbar Marg 9',
                  '44600',
                  'Thamel Street 25',
                  'nepal'],
        'en-nu': ['en-NU',
                  'Niue',
                  'Alofi',
                  'Main Road 12',
                  '4033',
                  'Commercial Centre 7',
                  'niue'],
        'en-nz': ['en-NZ',
                  'New Zealand',
                  'Wellington',
                  'Lambton Quay 42',
                  '6011',
                  'Courtenay Place 28',
                  'new-zealand'],
        'en-om': ['en-OM',
                  'Oman',
                  'Muscat',
                  'Sultan Qaboos Street 70',
                  '100',
                  'Al Khuwair Street 15',
                  'oman'],
        'en-pg': ['en-PG',
                  'Papua New Guinea',
                  'Port Moresby',
                  'Waigani Drive 33',
                  '131',
                  'Boroko Drive 18',
                  'papua-new-guinea'],
        'en-ph': ['en-PH',
                  'Philippines',
                  'Manila',
                  'Roxas Boulevard 55',
                  '1000',
                  'Ayala Avenue 25',
                  'philippines'],
        'en-pk': ['en-PK',
                  'Pakistan',
                  'Islamabad',
                  'Jinnah Avenue 28',
                  '44000',
                  'Constitution Avenue 19',
                  'pakistan'],
        'en-ps': ['en-PS',
                  'Palestine',
                  'Ramallah',
                  'Rukab Street 11',
                  '969',
                  'Al-Ersal Street 16',
                  'palestine'],
        'en-pw': ['en-PW',
                  'Palau',
                  'Ngerulmud',
                  'Capitol Complex 5',
                  '96940',
                  'Koror Road 22',
                  'palau'],
        'en-qa': ['en-QA',
                  'Qatar',
                  'Doha',
                  'Corniche Street 9',
                  '12345',
                  'Wadi Msheireb Street 18',
                  'qatar'],
        'en-rs': ['en-RS',
                  'Serbia',
                  'Belgrade',
                  'Knez Mihailova 33',
                  '11000',
                  'Terazije 15',
                  'serbia'],
        'en-rw': ['en-RW',
                  'Rwanda',
                  'Kigali',
                  'Nyarugenge Street 24',
                  '1100',
                  'KN 3 Road 9',
                  'rwanda'],
        'en-sa': ['en-SA',
                  'Saudi Arabia',
                  'Riyadh',
                  'Olaya Street 55',
                  '11547',
                  'King Fahd Road 108',
                  'saudi-arabia'],
        'en-sb': ['en-SB',
                  'Solomon Islands',
                  'Honiara',
                  'Mendana Avenue 12',
                  '131',
                  'Kukum Highway 17',
                  'solomon-islands'],
        'en-sd': ['en-SD',
                  'Sudan',
                  'Khartoum',
                  'Nile Street 64',
                  '11111',
                  'Airport Road 40',
                  'sudan'],
        'en-sg': ['en-SG',
                  'Singapore',
                  'Singapore',
                  'Orchard Road 999',
                  '238883',
                  'Marina Bay Street 18',
                  'singapore'],
        'en-sj': ['en-SJ',
                  'Svalbard and Jan Mayen',
                  'Longyearbyen',
                  'Vei 222-2',
                  '9170',
                  'Vei 508-10',
                  'svalbard-and-jan-mayen'],
        'en-sl': ['en-SL',
                  'Sierra Leone',
                  'Freetown',
                  'Siaka Stevens Street 51',
                  '1000',
                  'Lumley Beach Road 7',
                  'sierra-leone'],
        'en-sm': ['en-SM',
                  'San Marino',
                  'San Marino',
                  'Via del Voltone 13',
                  '47890',
                  'Contrada Omagnano 8',
                  'san-marino-en'],
        'en-so': ['en-SO',
                  'Somalia',
                  'Mogadishu',
                  'Maka Al Mukarama Road 78',
                  '2525',
                  'Zobe Junction 3',
                  'somalia'],
        'en-sr': ['en-SR',
                  'Suriname',
                  'Paramaribo',
                  'Kwattaweg 45',
                  '1000',
                  'Domineestraat 12',
                  'suriname'],
        'en-ss': ['en-SS',
                  'South Sudan',
                  'Juba',
                  'Tongping Road 10',
                  '00211',
                  'Ministries Road 7',
                  'south-sudan'],
        'en-st': ['en-ST',
                  'São Tomé and Príncipe',
                  'São Tomé',
                  'Independencia Avenue 42',
                  '00209',
                  'Amilcar Cabral Street 3',
                  'sao-tome-and-principe'],
        'en-sx': ['en-SX',
                  'Sint Maarten',
                  'Philipsburg',
                  'Frontstreet 28',
                  '0001',
                  'Back Street 12',
                  'sint-maarten'],
        'en-sy': ['en-SY',
                  'Syria',
                  'Damascus',
                  'Umayyad Square 6',
                  '1001',
                  'Mezzeh Highway 17',
                  'syria'],
        'en-sz': ['en-SZ',
                  'Eswatini',
                  'Mbabane',
                  'Gwamile Street 7',
                  'H100',
                  'Mhlambanyatsi Road 23',
                  'eswatini'],
        'en-tc': ['en-TC',
                  'Turks and Caicos Islands',
                  'Cockburn Town',
                  'Duke Street 11',
                  'TKCA 1ZZ',
                  'Leeward Highway 20',
                  'turks-and-caicos-islands'],
        'en-th': ['en-TH',
                  'Thailand',
                  'Bangkok',
                  'Sukhumvit Road 777',
                  '10110',
                  'Silom Road 32',
                  'thailand'],
        'en-tl': ['en-TL',
                  'Timor-Leste',
                  'Dili',
                  'Avenida de Portugal 19',
                  '0001',
                  'Rua Martires da Patria 22',
                  'timor-leste-en'],
        'en-tt': ['en-TT',
                  'Trinidad and Tobago',
                  'Port of Spain',
                  'Frederick Street 56',
                  '00000',
                  'Ariapita Avenue 22',
                  'trinidad-and-tobago'],
        'en-tz': ['en-TZ',
                  'Tanzania',
                  'Dodoma',
                  'Chama Avenue 47',
                  '40100',
                  'Gaddafi Road 33',
                  'tanzania'],
        'en-ug': ['en-UG',
                  'Uganda',
                  'Kampala',
                  'Kampala Road 11',
                  '256',
                  'Acacia Avenue 32',
                  'uganda'],
        'en-um': ['en-UM',
                  'U.S. Minor Outlying Islands',
                  'Baker Island',
                  'Main Street 1',
                  '96898',
                  'Harbor Road 7',
                  'u-s-minor-outlying-islands'],
        'en-us': ['en-US',
                  'United States',
                  'Washington, D.C.',
                  'Pennsylvania Avenue 1600',
                  '20500',
                  'Wall Street 15',
                  'united-states'],
        'en-va': ['en-VA',
                  'Vatican City',
                  'Vatican City',
                  'Vatican Square 1',
                  '00120',
                  "St. Peter's Square 7",
                  'vatican-city'],
        'en-vg': ['en-VG',
                  'British Virgin Islands',
                  'Road Town',
                  'Main Street 22',
                  'VG1110',
                  'Waterfront Drive 8',
                  'british-virgin-islands'],
        'en-vn': ['en-VN',
                  'Vietnam',
                  'Hanoi',
                  'Ba Dinh Square 1',
                  '10000',
                  'Tran Hung Dao Street 23',
                  'vietnam'],
        'en-ws': ['en-WS',
                  'Samoa',
                  'Apia',
                  'Beach Road 15',
                  'WS0979',
                  'Cross Island Road 11',
                  'samoa'],
        'en-xk': ['en-XK',
                  'Kosovo',
                  'Pristina',
                  'Mother Teresa Street 21',
                  '10000',
                  'Agim Ramadani Street 13',
                  'kosovo'],
        'en-ye': ['en-YE',
                  'Yemen',
                  "Sana'a",
                  '60 Meter Road 32',
                  '00967',
                  'Hadda Street 11',
                  'yemen'],
        'en-za': ['en-ZA',
                  'South Africa',
                  'Pretoria',
                  'Church Street 101',
                  '0002',
                  'Rivonia Road 90',
                  'south-africa'],
        'en-zm': ['en-ZM',
                  'Zambia',
                  'Lusaka',
                  'Cairo Road 27',
                  '10101',
                  'Thabo Mbeki Road 12',
                  'zambia'],
        'en-zw': ['en-ZW',
                  'Zimbabwe',
                  'Harare',
                  'Samora Machel Avenue 65',
                  '00263',
                  'Rotten Row 22',
                  'zimbabwe']},
 'es': {'es-ar': ['es-AR',
                  'Argentina',
                  'Buenos Aires',
                  'Avenida 9 de Julio 123',
                  '1000',
                  'Calle Florida 456',
                  'argentina'],
        'es-aw': ['es-AW',
                  'Aruba',
                  'Oranjestad',
                  'Caya G. F. Betico Croes 10',
                  '0001',
                  'Calle Comercial 20',
                  'aruba'],
        'es-bo': ['es-BO',
                  'Bolivia',
                  'Sucre',
                  'Avenida 16 de Julio 50',
                  '0900',
                  'Calle Mercado 25',
                  'bolivia'],
        'es-cl': ['es-CL',
                  'Chile',
                  'Santiago',
                  "Avenida Libertador Bernardo O'Higgins 70",
                  '8320000',
                  'Calle Providencia 80',
                  'chile'],
        'es-co': ['es-CO',
                  'Colombia',
                  'Bogotá',
                  'Carrera 7 #26',
                  '111711',
                  'Calle 80 #10',
                  'colombia'],
        'es-cr': ['es-CR',
                  'Costa Rica',
                  'San José',
                  'Avenida Central 5',
                  '1000',
                  'Calle Paseo Colón 40',
                  'costa-rica'],
        'es-cu': ['es-CU',
                  'Cuba',
                  'La Habana',
                  'Paseo del Prado 10',
                  '10100',
                  'Calle 23 #15',
                  'cuba'],
        'es-do': ['es-DO',
                  'República Dominicana',
                  'Santo Domingo',
                  'Avenida George Washington 60',
                  '10101',
                  'Calle El Conde 45',
                  'republica-dominicana'],
        'es-ec': ['es-EC',
                  'Ecuador',
                  'Quito',
                  'Avenida Amazonas 20',
                  '170143',
                  'Calle García Moreno 30',
                  'ecuador'],
        'es-eh': ['es-EH',
                  'Sahara Occidental',
                  'Laayoune',
                  'Avenida Smara 15',
                  '70000',
                  'Calle Hassan II 25',
                  'sahara-occidental'],
        'es-es': ['es-ES',
                  'España',
                  'Madrid',
                  'Gran Vía 30',
                  '28013',
                  'Calle Serrano 40',
                  'espana'],
        'es-gq': ['es-GQ',
                  'Guinea Ecuatorial',
                  'Malabo',
                  'Avenida Hassan II 25',
                  '00209',
                  'Calle Américo Vespucio 10',
                  'guinea-ecuatorial'],
        'es-gt': ['es-GT',
                  'Guatemala',
                  'Ciudad de Guatemala',
                  '6A Avenida 5',
                  '01001',
                  '7A Avenida 10',
                  'guatemala'],
        'es-hn': ['es-HN',
                  'Honduras',
                  'Tegucigalpa',
                  'Bulevar Suyapa 10',
                  '11101',
                  'Calle Los Alamos 35',
                  'honduras'],
        'es-mx': ['es-MX',
                  'México',
                  'Ciudad de México',
                  'Paseo de la Reforma 50',
                  '06500',
                  'Avenida Insurgentes Sur 300',
                  'mexico'],
        'es-ni': ['es-NI',
                  'Nicaragua',
                  'Managua',
                  'Avenida Bolívar 10',
                  '11001',
                  'Calle Bello Horizonte 30',
                  'nicaragua'],
        'es-pa': ['es-PA',
                  'Panamá',
                  'Ciudad de Panamá',
                  'Avenida Balboa 45',
                  '0819-05760',
                  'Calle 50 #22',
                  'panama'],
        'es-pe': ['es-PE',
                  'Perú',
                  'Lima',
                  'Avenida Abancay 50',
                  '15001',
                  'Calle Larco 40',
                  'peru'],
        'es-pr': ['es-PR',
                  'Puerto Rico',
                  'San Juan',
                  'Avenida Ponce de León 123',
                  '00901',
                  'Calle Fortaleza 55',
                  'puerto-rico'],
        'es-py': ['es-PY',
                  'Paraguay',
                  'Asunción',
                  'Avenida Mariscal López 100',
                  '1119',
                  'Calle Palma 50',
                  'paraguay'],
        'es-sv': ['es-SV',
                  'El Salvador',
                  'San Salvador',
                  'Alameda Roosevelt 25',
                  '1101',
                  'Bulevar de Los Héroes 20',
                  'el-salvador'],
        'es-uy': ['es-UY',
                  'Uruguay',
                  'Montevideo',
                  'Avenida 18 de Julio 130',
                  '11000',
                  'Calle Rambla 40',
                  'uruguay'],
        'es-ve': ['es-VE',
                  'Venezuela',
                  'Caracas',
                  'Avenida Bolívar 140',
                  '1010',
                  'Calle Andrés Bello 60',
                  'venezuela']},
 'et': {'et-ee': ['et-EE',
                  'Eesti',
                  'Tallinn',
                  'Vabaduse väljak 10',
                  '10146',
                  'Viru tänav 20',
                  'eesti']},
 'fi': {'fi-fi': ['fi-FI',
                  'Suomi',
                  'Helsinki',
                  'Senatsplatsen 1',
                  '00170',
                  'Aleksanterinkatu 20',
                  'suomi']},
 'fr': {'fr-bf': ['fr-BF',
                  'Burkina Faso',
                  'Ouagadougou',
                  "Avenue de l'Indépendance 10",
                  '01',
                  'Rue de la Paix 20',
                  'burkina-faso'],
        'fr-bi': ['fr-BI',
                  'Burundi',
                  'Bujumbura',
                  "Boulevard de l'Uprona 50",
                  '1100',
                  'Avenue de la Liberté 35',
                  'burundi'],
        'fr-bj': ['fr-BJ',
                  'Bénin',
                  'Cotonou',
                  'Avenue Clozel 15',
                  '3000',
                  "Rue de l'Entente 25",
                  'benin'],
        'fr-bl': ['fr-BL',
                  'Saint-Barthélemy',
                  'Gustavia',
                  'Rue du Bord de Mer 1',
                  '97133',
                  'Rue de la République 5',
                  'saint-barthelemy'],
        'fr-ca': ['fr-CA',
                  'Canada',
                  'Montréal',
                  'Rue Sainte-Catherine 100',
                  'H2W 1N1',
                  'Boulevard René-Lévesque 75',
                  'canada-fr'],
        'fr-cd': ['fr-CD',
                  'République Démocratique du Congo',
                  'Kinshasa',
                  'Avenue des Huileries 5',
                  '1000',
                  'Boulevard du 30 Juin 20',
                  'republique-democratique-du-congo'],
        'fr-cf': ['fr-CF',
                  'République Centrafricaine',
                  'Bangui',
                  'Avenue des Martyrs 8',
                  '1010',
                  'Rue de France 12',
                  'republique-centrafricaine'],
        'fr-cg': ['fr-CG',
                  'République du Congo',
                  'Brazzaville',
                  'Avenue du Général de Gaulle 15',
                  '2000',
                  'Rue Makabandilou 10',
                  'republique-du-congo'],
        'fr-ci': ['fr-CI',
                  "Côte d'Ivoire",
                  'Abidjan',
                  'Boulevard de la République 35',
                  '5000',
                  'Avenue Houphouët-Boigny 30',
                  'cote-d-ivoire'],
        'fr-cm': ['fr-CM',
                  'Cameroun',
                  'Yaoundé',
                  'Avenue Ahmadou Ahidjo 25',
                  '3000',
                  'Boulevard de la Liberté 40',
                  'cameroun'],
        'fr-dj': ['fr-DJ',
                  'Djibouti',
                  'Djibouti',
                  'Place Lagarde 2',
                  '1000',
                  'Avenue Georges Clemenceau 10',
                  'djibouti'],
        'fr-dz': ['fr-DZ',
                  'Algérie',
                  'Alger',
                  'Boulevard Zighout Youcef 100',
                  '16000',
                  'Avenue de la Liberté 50',
                  'algerie'],
        'fr-fr': ['fr-FR',
                  'France',
                  'Paris',
                  'Champs-Élysées 10',
                  '75008',
                  'Rue de Rivoli 30',
                  'france'],
        'fr-ga': ['fr-GA',
                  'Gabon',
                  'Libreville',
                  'Boulevard Triomphal 20',
                  '6000',
                  'Rue de la Paix 45',
                  'gabon'],
        'fr-gn': ['fr-GN',
                  'Guinée',
                  'Conakry',
                  'Avenue de la République 15',
                  '2000',
                  'Rue de France 25',
                  'guinee'],
        'fr-gp': ['fr-GP',
                  'Guadeloupe',
                  'Pointe-à-Pitre',
                  'Rue Frébault 5',
                  '97110',
                  'Rue Schoelcher 8',
                  'guadeloupe'],
        'fr-ht': ['fr-HT',
                  'Haïti',
                  'Port-au-Prince',
                  'Rue Capois 10',
                  '6110',
                  'Avenue Jean-Jacques Dessalines 20',
                  'haiti'],
        'fr-km': ['fr-KM',
                  'Comores',
                  'Moroni',
                  "Avenue de l'Indépendance 5",
                  '2000',
                  'Rue du Commerce 30',
                  'comores'],
        'fr-lu': ['fr-LU',
                  'Luxembourg',
                  'Luxembourg',
                  'Avenue de la Liberté 50',
                  'L-1930',
                  'Rue Royale 10',
                  'luxembourg'],
        'fr-ma': ['fr-MA',
                  'Maroc',
                  'Rabat',
                  'Avenue Mohammed V 40',
                  '10000',
                  'Boulevard de la Résistance 25',
                  'maroc'],
        'fr-mc': ['fr-MC',
                  'Monaco',
                  'Monaco',
                  "Avenue d'Ostende 15",
                  '98000',
                  'Boulevard des Moulins 10',
                  'monaco'],
        'fr-mf': ['fr-MF',
                  'Saint-Martin',
                  'Marigot',
                  'Rue de la Liberté 2',
                  '97150',
                  'Rue de Hollande 5',
                  'saint-martin'],
        'fr-mg': ['fr-MG',
                  'Madagascar',
                  'Antananarivo',
                  "Avenue de l'Indépendance 10",
                  '101',
                  'Rue Ratsimilaho 20',
                  'madagascar'],
        'fr-ml': ['fr-ML',
                  'Mali',
                  'Bamako',
                  'Avenue de la Nation 15',
                  '1000',
                  'Rue de la Paix 30',
                  'mali'],
        'fr-mq': ['fr-MQ',
                  'Martinique',
                  'Fort-de-France',
                  'Rue Victor Hugo 1',
                  '97200',
                  'Rue de la Liberté 10',
                  'martinique'],
        'fr-mr': ['fr-MR',
                  'Mauritanie',
                  'Nouakchott',
                  'Avenue Gamal Abdel Nasser 5',
                  '0001',
                  'Rue de la République 20',
                  'mauritanie'],
        'fr-nc': ['fr-NC',
                  'Nouvelle-Calédonie',
                  'Nouméa',
                  'Avenue de la Victoire 30',
                  '98800',
                  'Rue du Général Mangin 15',
                  'nouvelle-caledonie'],
        'fr-ne': ['fr-NE',
                  'Niger',
                  'Niamey',
                  'Avenue du Général de Gaulle 10',
                  '9000',
                  'Rue de la République 25',
                  'niger'],
        'fr-pf': ['fr-PF',
                  'Polynésie Française',
                  'Papeete',
                  'Boulevard Pomare 20',
                  '98713',
                  'Avenue du Prince Hinoi 10',
                  'polynesie-francaise'],
        'fr-pm': ['fr-PM',
                  'Saint-Pierre-et-Miquelon',
                  'Saint-Pierre',
                  'Rue Albert Briand 5',
                  '97500',
                  'Rue du 11 Novembre 10',
                  'saint-pierre-et-miquelon'],
        'fr-re': ['fr-RE',
                  'La Réunion',
                  'Saint-Denis',
                  'Rue de Paris 15',
                  '97400',
                  'Rue du Général de Gaulle 20',
                  'la-reunion'],
        'fr-sc': ['fr-SC',
                  'Seychelles',
                  'Victoria',
                  'Rue de la République 5',
                  '0000',
                  "Avenue de l'Indépendance 10",
                  'seychelles'],
        'fr-sn': ['fr-SN',
                  'Sénégal',
                  'Dakar',
                  'Avenue Cheikh Anta Diop 20',
                  '5000',
                  'Rue de Thann 35',
                  'senegal'],
        'fr-td': ['fr-TD',
                  'Tchad',
                  "N'Djamena",
                  'Avenue Charles de Gaulle 15',
                  '1000',
                  'Rue de la Liberté 30',
                  'tchad'],
        'fr-tf': ['fr-TF',
                  'Terres Australes Françaises',
                  'Port-aux-Français',
                  'Rue Principale 1',
                  '98400',
                  'Rue des Manchots 2',
                  'terres-australes-francaises'],
        'fr-tg': ['fr-TG',
                  'Togo',
                  'Lomé',
                  'Boulevard du 13 Janvier 10',
                  '1000',
                  'Rue des Flamboyants 25',
                  'togo'],
        'fr-tn': ['fr-TN',
                  'Tunisie',
                  'Tunis',
                  'Avenue Habib Bourguiba 50',
                  '1000',
                  'Rue de Marseille 40',
                  'tunisie'],
        'fr-wf': ['fr-WF',
                  'Wallis-et-Futuna',
                  'Mata-Utu',
                  'Rue Kafika 1',
                  '98600',
                  'Rue Sagato Soane 5',
                  'wallis-et-futuna'],
        'fr-yt': ['fr-YT',
                  'Mayotte',
                  'Mamoudzou',
                  'Rue du Commerce 10',
                  '97600',
                  'Avenue du Général de Gaulle 15',
                  'mayotte']},
 'hu': {'hu-hu': ['hu-HU',
                  'Magyarország',
                  'Budapest',
                  'Kossuth tér 1-3.',
                  '1055',
                  'Váci utca 20',
                  'magyarorszag']},
 'id': {'id-id': ['id-ID',
                  'Indonesia',
                  'Jakarta',
                  'Jalan Medan Merdeka Selatan No.1',
                  '10110',
                  'Jalan Thamrin No. 20',
                  'indonesia']},
 'it': {'it-it': ['it-IT',
                  'Italia',
                  'Roma',
                  'Piazza Venezia 1',
                  '00187',
                  'Via del Corso 20',
                  'italia'],
        'it-sm': ['it-SM',
                  'San Marino',
                  'Città di San Marino',
                  'Piazza della Libertà 1',
                  '47890',
                  'Via del Teatro 20',
                  'san-marino-it']},
 'ja': {'ja-jp': ['ja-JP',
                  '日本',
                  '東京',
                  '千代田区丸の内1-1',
                  '100-0005',
                  '渋谷区道玄坂20',
                  'ri-ben']},
 'ko': {'ko-kp': ['ko-KP',
                  '조선민주주의인민공화국',
                  '평양',
                  '김일성광장 1',
                  '100-000',
                  '독립대로 20',
                  'joseonminjujuyiinmingonghwagug'],
        'ko-kr': ['ko-KR',
                  '대한민국',
                  '서울',
                  '태평로 1',
                  '04544',
                  '강남대로 20',
                  'daehanmingug']},
 'lt': {'lt-lt': ['lt-LT',
                  'Lietuva',
                  'Vilnius',
                  'Gedimino pr. 1',
                  '01103',
                  'Pilies g. 20',
                  'lietuva']},
 'lv': {'lv-lv': ['lv-LV',
                  'Latvija',
                  'Rīga',
                  'Brīvības bulvāris 1',
                  'LV-1050',
                  'Elizabetes iela 20',
                  'latvija']},
 'nb': {'nb-no': ['nb-NO',
                  'Norge',
                  'Oslo',
                  'Stortingsgata 1',
                  '0161',
                  'Karl Johans gate 20',
                  'norge']},
 'nl': {'nl-be': ['nl-BE',
                  'België',
                  'Brussel',
                  'Wetstraat 1',
                  '1000',
                  'Nieuwstraat 20',
                  'belgie'],
        'nl-bq': ['nl-BQ',
                  'Bonaire',
                  'Kralendijk',
                  'Plasa Wilhelmina 1',
                  'Caribbean Netherlands',
                  'Kaya Grandi 20',
                  'bonaire'],
        'nl-cw': ['nl-CW',
                  'Curaçao',
                  'Willemstad',
                  'Handelskade 1',
                  'Curaçao',
                  'Breedestraat 20',
                  'curacao'],
        'nl-nl': ['nl-NL',
                  'Nederland',
                  'Amsterdam',
                  'Dam 1',
                  '1012 NP',
                  'Kalverstraat 20',
                  'nederland']},
 'pl': {'pl-pl': ['pl-PL',
                  'Polska',
                  'Warszawa',
                  'Plac Zamkowy 1',
                  '00-277',
                  'Nowy Świat 20',
                  'polska']},
 'pt': {'pt-ao': ['pt-AO',
                  'Angola',
                  'Luanda',
                  'Avenida 4 de Fevereiro 100',
                  '1000',
                  'Rua Amílcar Cabral 20',
                  'angola'],
        'pt-br': ['pt-BR',
                  'Brasil',
                  'São Paulo',
                  'Avenida Paulista 1578',
                  '01310-200',
                  'Rua Augusta 501',
                  'brasil'],
        'pt-cv': ['pt-CV',
                  'Cabo Verde',
                  'Praia',
                  'Avenida Cidade de Lisboa 30',
                  '7600',
                  'Rua Serpa Pinto 10',
                  'cabo-verde'],
        'pt-gw': ['pt-GW',
                  'Guiné-Bissau',
                  'Bissau',
                  'Avenida Amílcar Cabral 50',
                  '1001',
                  'Rua José Carlos Schwarz 15',
                  'guine-bissau'],
        'pt-mz': ['pt-MZ',
                  'Moçambique',
                  'Maputo',
                  'Avenida Julius Nyerere 1111',
                  '1010',
                  'Rua Eduardo Mondlane 25',
                  'mocambique'],
        'pt-pt': ['pt-PT',
                  'Portugal',
                  'Lisboa',
                  'Avenida da Liberdade 120',
                  '1250-145',
                  'Rua Augusta 50',
                  'portugal'],
        'pt-st': ['pt-ST',
                  'São Tomé e Príncipe',
                  'São Tomé',
                  'Avenida Marginal 12 de Julho 5',
                  '1000',
                  'Rua da Independência 10',
                  'sao-tome-e-principe'],
        'pt-tl': ['pt-TL',
                  'Timor-Leste',
                  'Díli',
                  'Avenida de Portugal 20',
                  '1000',
                  'Rua 28 de Novembro 15',
                  'timor-leste-pt']},
 'ro': {'ro-md': ['ro-MD',
                  'Republica Moldova',
                  'Chișinău',
                  'Bulevardul Ștefan cel Mare și Sfânt 1',
                  '2001',
                  'Strada București 20',
                  'republica-moldova'],
        'ro-ro': ['ro-RO',
                  'România',
                  'București',
                  'Piața Revoluției 1',
                  '010375',
                  'Bulevardul Magheru 20',
                  'romania']},
 'ru': {'ru-am': ['ru-AM',
                  'Армения',
                  'Ереван',
                  'Проспект Маршала Баграмяна 1',
                  '375019',
                  'Улица Абовяна 5',
                  'armeniia'],
        'ru-az': ['ru-AZ',
                  'Азербайджан',
                  'Баку',
                  'Проспект Нефтяников 10',
                  '1010',
                  'Улица Гадрутская 20',
                  'azerbaidzhan-ru'],
        'ru-by': ['ru-BY',
                  'Беларусь',
                  'Минск',
                  'Проспект Независимости 100',
                  '220050',
                  'Улица Коммунистическая 25',
                  'belarus'],
        'ru-ge': ['ru-GE',
                  'Грузия',
                  'Тбилиси',
                  'Проспект Руставели 40',
                  '0108',
                  'Улица Чавчавадзе 15',
                  'gruziia'],
        'ru-kg': ['ru-KG',
                  'Киргизия',
                  'Бишкек',
                  'Проспект Чуй 100',
                  '720001',
                  'Улица Боконбаева 20',
                  'kirgiziia'],
        'ru-kz': ['ru-KZ',
                  'Казахстан',
                  'Астана',
                  'Проспект Мангилик Ел 55',
                  '010000',
                  'Улица Кенесары 10',
                  'kazakhstan'],
        'ru-mn': ['ru-MN',
                  'Монголия',
                  'Улан-Батор',
                  'Проспект Сухэ-Батора 5',
                  '210646',
                  'Улица Сансар 20',
                  'mongoliia'],
        'ru-ru': ['ru-RU',
                  'Россия',
                  'Москва',
                  'Тверская улица 7',
                  '125009',
                  'Арбат 15',
                  'rossiia'],
        'ru-tj': ['ru-TJ',
                  'Таджикистан',
                  'Душанбе',
                  'Проспект Рудаки 50',
                  '734025',
                  'Улица И. Сомони 30',
                  'tadzhikistan'],
        'ru-tm': ['ru-TM',
                  'Туркменистан',
                  'Ашхабад',
                  'Проспект Мактумкули 70',
                  '744000',
                  'Улица Героя Туркменистана Атаева 5',
                  'turkmenistan-ru'],
        'ru-ua': ['ru-UA',
                  'Украина',
                  'Киев',
                  'Хрещатик 50',
                  '01001',
                  'Улица Владимирская 20',
                  'ukraina-ru'],
        'ru-uz': ['ru-UZ',
                  'Узбекистан',
                  'Ташкент',
                  'Проспект Мустакиллик 30',
                  '100000',
                  'Улица Амира Темура 15',
                  'uzbekistan']},
 'sk': {'sk-sk': ['sk-SK',
                  'Slovensko',
                  'Bratislava',
                  'Námestie SNP 1',
                  '81101',
                  'Obchodná ulica 20',
                  'slovensko']},
 'sl': {'sl-si': ['sl-SI',
                  'Slovenija',
                  'Ljubljana',
                  'Prešernov trg 1',
                  '1000',
                  'Slovenska cesta 20',
                  'slovenija']},
 'sv': {'sv-ax': ['sv-AX',
                  'Åland',
                  'Mariehamn',
                  'Torggatan 10',
                  '22100',
                  'Nybovägen 20',
                  'aland'],
        'sv-se': ['sv-SE',
                  'Sverige',
                  'Stockholm',
                  'Kungsgatan 10',
                  '11143',
                  'Sveavägen 20',
                  'sverige']},
 'tr': {'tr-az': ['tr-AZ',
                  'Azerbaycan',
                  'Bakü',
                  'Neftçilar Prospekti 10',
                  '1010',
                  'Qədrut Küçəsi 20',
                  'azerbaycan-tr'],
        'tr-tm': ['tr-TM',
                  'Türkmenistan',
                  'Aşkabat',
                  'Mahtumkuli prospekti 70',
                  '744000',
                  'Garaşsyzlyk şayoli 5',
                  'turkmenistan-tr'],
        'tr-tr': ['tr-TR',
                  'Türkiye',
                  'Ankara',
                  'Atatürk Bulvarı 10',
                  '06050',
                  'Tunalı Hilmi Caddesi 20',
                  'turkiye']},
 'uk': {'uk-ua': ['uk-UA',
                  'Україна',
                  'Київ',
                  'Хрещатик 50',
                  '01001',
                  'Вулиця Володимирська 20',
                  'ukrayina-uk']},
 'zh': {'zh-cn': ['zh-CN',
                  '中国',
                  '北京',
                  '长安街1号',
                  '100000',
                  '王府井大街20号',
                  'zhong-guo'],
        'zh-hk': ['zh-HK',
                  '香港',
                  '中環',
                  '皇后大道中1號',
                  '999077',
                  '彌敦道20號',
                  'xiang-gang'],
        'zh-mo': ['zh-MO',
                  '澳門',
                  '澳門半島',
                  '南灣大馬路1號',
                  '999078',
                  '巴素打路20號',
                  'ao-men'],
        'zh-tw': ['zh-TW', '台灣', '台北', '中正路1號', '10048', '忠孝東路20號', 'tai-wan']}}


try:
    with connect_database.cursor() as cursor:
        rank = 5
        for lang, details in data.items():
            for key, value in details.items():
                # Підготовка даних для вставки
                name = f"{value[0]} - {value[1]}"
                key_value = value[-1]
                description = "SEO"
                
                # SQL запит для вставки
                sql = "INSERT INTO `modx_context` (`key`, `name`, `description`, `rank`) VALUES (%s, %s, %s, %s)"
                
                cursor.execute(sql, (key_value, name, description, rank))
                rank += 1
                
    # Збереження змін
    connect_database.commit()
    
finally:
    connect_database.close()