language_tld_mapping = {
    'Arabic': ['ar',
               'ps',
               'tn',
               'abudhabi',
               'sa',
               'com.sa',
               'com.eg',
               'blogspot.com.eg',
               'om',
               'ly',
               'com.qa',
               'ae',
               'jo',
               'com.lb',
               'org.sa',
               'blogspot.ae',
               'qa',
               'blogspot.qa',
               'dz', 'eg', 'ma', 'mr', 'sd', 'so',
               'dj', 'er', 'ma'],
    'Azerbaijani': ['az'],
    'Bulgarian': ['bg'],
    'Chinese': ['zh',
                'xn--io0a7i',
                'xn--fiqs8s',
                'xn--q9jyb4c',
                'com.tw',
                'blogspot.tw',
                'xn--3ds443g',
                'hk',
                'edu.hk',
                'cyou',
                'xn--5tzm5g',
                'com.cn',
                'xn--vhquv',
                'xn--xhq521b',
                'xn--ngbc5azd',
                'xin',
                'gov.hk',
                'edu.cn',
                'wang',
                'gov.tw',
                'blogspot.hk',
                'org.hk',
                'ac.cn',
                'xn--55qx5d',
                'xn--vuq861b',
                'sh.cn',
                'idv.tw',
                'org.tw',
                'tw',
                'xn--t60b56a',
                'fan',
                'cn',
                'taipei',
                'gov.cn',
                'xn--hxt814e',
                'org.cn',
                'xn--rhqv96g',
                'xn--fiq228c5hs',
                'net.cn',
                'xn--6qq986b3xl',
                'ren',
                'com.hk', 'asia', 'xn--g2xx48c'],
    'Croatian': ['hr'],
    'Czech': ['cs',
              'xn--czrs0t',
              'blogspot.cz',
              'xn--czru2d',
              'xn--czr694b',
              'cz'],
    'Danish': ['da', 'dk', 'blogspot.dk', 'fo'],
    'Dutch': ['nl',
              'gent',
              'gratis',
              'nl',
              'blogspot.be',
              'blogspot.nl',
              'vlaanderen',
              'amsterdam'],
    'English': ['en',
                'us',
                'so',
                'go.tz',
                'vn',
                'net.in',
                'sale',
                'lk',
                'is',
                'physio',
                'shiksha',
                'restaurant',
                'edu.bd',
                'top',
                'eco',
                'leics.sch.uk',
                'organic',
                'security',
                'pet',
                'pictures',
                'world',
                'systems',
                'fitness',
                'com',
                'yoga',
                'blackfriday',
                'loans',
                'onlinehome.us',
                'press',
                'property',
                'software',
                'basketball',
                'bc.ca',
                'creditunion',
                'in',
                'sydney',
                'gov.za',
                'durban',
                'ab.ca',
                'singles',
                'ai',
                'co.ke',
                'vic.edu.au',
                'mom',
                'soccer',
                'diamonds',
                'airforce',
                'studio',
                'university',
                'vacations',
                'estate',
                'watch',
                'build',
                'broadway',
                'northumberland.sch.uk',
                'hockey',
                'ghost.io',
                'coach',
                'beauty',
                'tips',
                'or.tz',
                'care',
                'red',
                'reviews',
                'how',
                'rip',
                'training',
                'gripe',
                'recipes',
                'repair',
                'porn',
                'video',
                'notts.sch.uk',
                'actor',
                'horse',
                'plus',
                'pharmacy',
                'supplies',
                'tube',
                'jewelry',
                'exposed',
                'camera',
                'org.uk',
                'staffs.sch.uk',
                'investments',
                'llc',
                'wales',
                'christmas',
                'derbyshire.sch.uk',
                'loan',
                'kids',
                'uk',
                'biz',
                'auction',
                'guru',
                'show',
                'gc.ca',
                'ky',
                'surgery',
                'properties',
                'page',
                'org.au',
                'rugby',
                'website',
                'hair',
                'carrd.co',
                'blogspot.com.au',
                'tax',
                'com.mt',
                'gift',
                'gloucs.sch.uk',
                'farm',
                'lancs.sch.uk',
                'nyc',
                'digital',
                'homes',
                'belfast.ni.sch.uk',
                'party',
                'norfolk.sch.uk',
                'tattoo',
                'xxx',
                'ac',
                'suffolk.sch.uk',
                'jobs',
                'vc',
                'movie',
                'insure',
                'shoes',
                'cloud',
                'hosting',
                'feedback',
                'cumbria.sch.uk',
                'holdings',
                'tickets',
                'bham.sch.uk',
                'limo',
                'blogspot.sg',
                'co.uk',
                'poker',
                'voyage',
                'durham.sch.uk',
                'gives',
                'limited',
                'com.sg',
                'wedding',
                'enterprises',
                'army',
                'online',
                'country',
                'racing',
                'gov.in',
                'direct',
                'kitchen',
                'energy',
                'contractors',
                'site',
                'wa.edu.au',
                'hants.sch.uk',
                'inc',
                'oxon.sch.uk',
                'radio',
                'graphics',
                'com.gh',
                'marketing',
                'gs',
                'flowers',
                'creditcard',
                'broker',
                'makeup',
                'webcam',
                'chat',
                'qpon',
                'bike',
                'cash',
                'management',
                'net.nz',
                'vet',
                'cooking',
                'cpa',
                'engineer',
                'gallery',
                'company',
                'mba',
                'co.nz',
                'rehab',
                'dentist',
                'florist',
                'equipment',
                'democrat',
                'forex',
                'me',
                'institute',
                'coupons',
                'healthcare',
                'ink',
                'baby',
                'warwickshire.sch.uk',
                'golf',
                'bible',
                'bargains',
                'cruises',
                'ltd.uk',
                'museum',
                'bingo',
                'supply',
                'co.bw',
                'org.za',
                'day',
                'com.au',
                'doctor',
                'vegas',
                'live',
                'ac.in',
                'co.in',
                'repl.co',
                'vote',
                'game',
                'org',
                'essex.sch.uk',
                'cambs.sch.uk',
                'wiki',
                'domain.name',
                'forsale',
                'contact',
                'exchange',
                'ski',
                'cool',
                'catholic.edu.au',
                'w-sussex.sch.uk',
                'land',
                'help',
                'ms',
                'au',
                'autos',
                'co.ug',
                'casino',
                'tc',
                'ug',
                'hospital',
                'ltd',
                'on.ca',
                'tech',
                'accountant',
                'house',
                'click',
                'law',
                'fm',
                'je',
                'associates',
                'blog',
                'co.zw',
                'ac.nz',
                'sg',
                'games',
                'vg',
                'domains',
                'co.za',
                'kiwi',
                'lighting',
                'place',
                'gi',
                'builders',
                'space',
                'irish',
                'solutions',
                'photography',
                'attorney',
                'eu',
                'men',
                'govt.nz',
                'bm',
                'review',
                'film',
                'financial',
                'me.uk',
                'nic.in',
                'select',
                'ie',
                'aero',
                'camp',
                'worcs.sch.uk',
                'xyz',
                'link',
                'faith',
                'io',
                'lawyer',
                'lpages.co',
                'plumbing',
                'nz',
                'careers',
                'cleaning',
                'asn.au',
                'cornwall.sch.uk',
                'am',
                'cricket',
                'download',
                'pro',
                'whoswho',
                'gov',
                'academy',
                'fish',
                'realtor',
                'sucks',
                'report',
                'mobi',
                'im',
                'social',
                'lincs.sch.uk',
                'group',
                'city',
                'surrey.sch.uk',
                'computer',
                'edu.in',
                'international',
                'clinic',
                'lgbt',
                'claims',
                'diet',
                'now.sh',
                'guide',
                'com.na',
                'cam',
                'credit',
                'industries',
                'rocks',
                'school.nz',
                'charity',
                'photos',
                'blogspot.ie',
                'org.nz',
                'leeds.sch.uk',
                'melbourne',
                'somerset.sch.uk',
                'email',
                'dog',
                'edu.au',
                'edu.sg',
                'shopping',
                'flights',
                'github.io',
                'stream',
                'pics',
                'legal',
                'org.pk',
                'life',
                'gov.pk',
                'dating',
                'rw',
                'rodeo',
                'fyi',
                'career',
                'gifts',
                'boats',
                'cards',
                'london',
                'boston',
                'kent.sch.uk',
                'neustar',
                'best',
                'onl',
                'republican',
                'glasgow.sch.uk',
                'net',
                'love',
                'ca',
                'family',
                'global',
                'dev',
                'liverpool.sch.uk',
                'glitch.me',
                'surf',
                'bot',
                'support',
                'devon.sch.uk',
                'photo',
                'bond',
                'ws',
                'college',
                'blogspot.ca',
                'sexy',
                'observer',
                'skin',
                'trading',
                'ag',
                'cheshire.sch.uk',
                'parts',
                'org.sg',
                'tires',
                'as',
                'win',
                'works',
                'giving',
                'black',
                'icu',
                'mortgage',
                'fit',
                'org.ph',
                'readthedocs.io',
                'gitlab.io',
                'toys',
                'gay',
                'network',
                'n-yorks.sch.uk',
                'football',
                'study',
                'navy',
                'mt',
                'lease',
                'gov.au',
                'herts.sch.uk',
                'blogspot.in',
                'com.ph',
                'net.au',
                'sport',
                'wilts.sch.uk',
                'accountants',
                'synology.me',
                'compare',
                'cheap',
                'quest',
                'lol',
                'menu',
                'capetown',
                'guitars',
                'news',
                'monster',
                'directory','bw', 'bi', 'cv', 'km', 'dj', 'eg', 'er', 'sz', 'et', 'gm', 'gh', 'gn', 'gw', 'ke', 'ls', 'lr', 'ly', 'mw', 'mu', 'yt', 'na', 'ne', 'ng', 're', 'rw', 'sh', 'st', 'sl', 'so', 'za', 'ss', 'sd', 'tz', 'ug', 'zm', 'zw',
                'scot', 'blogspot.co.za', 'mb.ca', 'edu.ph', 'pantheonsite.io', 'tv', 'cymru', 'africa', 'bz', 'sh', 'to'],
    'Estonian': ['et', 'edu.ee', 'ee'],
    'Finnish': ['fi', 'blogspot.fi', 'fund', 'pink'],
    'French': ['fr',
               'lu',
               'luxury',
               'pm',
               'mc',
               'notaires.fr',
               'gg',
               'free.fr',
               'ml',
               'productions',
               'ovh',
               'luxe',
               'archi',
               'frl',
               'art',
               'nc',
               'qc.ca',
               'wine',
               're',
               'ci',
               'ma',
               'gouv.fr',
               'mg',
               'quebec',
               'maison',
               'chirurgiens-dentistes.fr',
               'corsica',
               'paris',
               'salon',
               'sn',
               'asso.fr',
               'pf',
               'brussels',
               'blogspot.fr',
               'boutique',
               'cm',
               'sc',
               'cf',
               'be',
               'cd',
               'cfd',
               'mu',
               'alsace',
               'cafe',
               'sarl',
               'com.tn',
               'leclerc',
               'ga', 'dz', 'bj', 'bf', 'td', 'gq', 'mr', 'mz', 'tg',
               'km', 'mg', 'bi', 'cf', 'cd', 'ci', 'gq', 'dj', 'cg', 'bj', 'sn', 'tg', 'ne', 'bf', 'tg', 'ga', 'ml', 'mr', 'mu', 're', 'rw', 'sc', 'sh', 'st', 'sz', 'td', 'tn', 'mg', 'yt', 'pf', 'nc', 'wf', 'tf'],
    'German': ['de',
               'beepworld.de',
               'allfinanz',
               'reisen',
               'schwarz',
               'versicherung',
               'dvag',
               'com.de',
               'or.at',
               'zuerich',
               'blogspot.co.at',
               'haus',
               'immo',
               'schule',
               'reise',
               'wien',
               'kaufen',
               'koeln',
               'ruhr',
               'cologne',
               'beer',
               'at',
               'gv.at',
               'berlin',
               'tirol',
               'swiss',
               'saarland',
               'gmbh',
               'ac.at',
               'blogspot.de',
               'immobilien',
               'ch',
               'hamburg',
               'jetzt',
               'nrw',
               'li',
               'audi',
               'co.at',
               'bayern',
               'run'],
    'Greek': ['el', 'edu.gr', 'blogspot.gr', 'gov.gr', 'com.gr', 'gr', 'com.cy', 'org.cy', 'al'],
    'Hungarian': ['hu', 'co.hu', 'blogspot.hu', 'atw.hu', 'ba', 'rs'],
    'Indonesian': ['id',
                   'co.id',
                   'id.au',
                   'my.id',
                   'web.id',
                   'desa.id',
                   'or.id',
                   'ac.id',
                   'ind.in',
                   'sch.id',
                   'blogspot.co.id',
                   'go.id'],
    'Italian': ['it',
                'sm',
                'srl',
                'edu.it',
                'blogspot.it',
                'bz.it',
                'pizza',
                'roma.it',
                'milano.it', 'ba'],
    'Japanese': ['ja',
                 'nagoya',
                 'kyoto',
                 'tokyo',
                 'or.jp',
                 'osaka',
                 'ne.jp',
                 'yokohama',
                 'ac.jp',
                 'co.jp',
                 'blogspot.jp',
                 'moe',
                 'ed.jp',
                 'jp',
                 'ninja',
                 'okinawa',
                 'ryukyu',
                 'go.jp',
                 'tokyo.jp',
                 'gr.jp'],
    'Kazakh': ['kk', 'kz', 'edu.kz', 'com.kz'],
    'Korean': ['ko',
               'go.kr',
               'kr',
               'hs.kr',
               'kim',
               'ms.kr',
               'ac.kr',
               'xn--3e0b707e',
               'blogspot.kr',
               'co.kr',
               're.kr',
               'or.kr'],
    'Kyrgyz': ['kg'],
    'Latvian': ['lv', 'lat'],
    'Lithuanian': ['lt'],
    'Norwegian': ['nb', 'blogspot.no', 'kommune.no', 'no'],
    'Other': ['club'],
    'Persian': ['r98.ir', 'avablog.ir', 'avablog.ir', 'co.ir', 'ac.ir'],
    'Polish': ['pl',
               'krakow.pl',
               'zgora.pl',
               'pila.pl',
               'express',
               'elblag.pl',
               'home.pl',
               'olsztyn.pl',
               'rybnik.pl',
               'com.pl',
               'org.pl',
               'opole.pl',
               'net.pl',
               'bydgoszcz.pl',
               'warszawa.pl',
               'wroclaw.pl',
               'gop',
               'szczecin.pl',
               'services',
               'czest.pl',
               'rzeszow.pl',
               'info.pl',
               'waw.pl',
               'slask.pl',
               'gov.pl',
               'radom.pl',
               'katowice.pl',
               'malopolska.pl',
               'slupsk.pl',
               'edu.pl',
               'kalisz.pl',
               'bialystok.pl'],
    'Portuguese': ['pt',
                   'blogspot.pt',
                   'gq',
                   'rio',
                   'coop.br',
                   'blog.br',
                   'srv.br',
                   'com.pt',
                   'gov.br',
                   'edu.br',
                   'eng.br',
                   'cx',
                   'com.br',
                   'net.br',
                   'imb.br',
                   'cab',
                   'mg.gov.br',
                   'sp.gov.br',
                   'eco.br',
                   'blogs.sapo.pt',
                   'pro.br',
                   'art.br',
                   'agr.br',
                   'co.ao',
                   'org.br',
                   'med.br',
                   'page.tl',
                   'st',
                   'adv.br',
                   'blogspot.com.br',
                   'cv',
                   'ind.br',
                   'cnt.br',
                   'inf.br',
                   'arq.br',
                   'ao', 'gw', 'mz',
                   'cv', 'st', 'sc', 'sh', 'sz', 'mu', 'mz', 'ao'],
    'Romanian': ['ro', 'md', 'blogspot.ro', 'com.ro', 'ba', 'rs'],
    'Russian': ['ru',
                'moscow',
                'taxi',
                'ooo',
                'xn--d1acj3b',
                'su',
                'vodka',
                'xn--p1acf',
                'xn--3bst00m',
                'memorial',
                'xn--nqv7f',
                'by',
                'xn--90ais',
                'center',
                'kred',
                'xn--c1avg',
                'do.am',
                'xn--80asehdb',
                'xn--p1ai',
                'xn--j1amh',
                'xn--6frz82g',
                'vin',
                'xn--80aswg',
                'xn--80adxhks', 'tatar', 'tj', 'co.il', 'xn--9dbq2a'],
    'Slovak': ['sk'],
    'Slovenian': ['sl', 'si'],
    'Spanish': ['es',
                'gq',
                'seat',
                'juegos',
                'org.co',
                'es.kr',
                'cat',
                'tienda',
                'ad',
                'mx',
                'com.py',
                'pe',
                'futbol',
                'abogado',
                'com.ni',
                'blogspot.pe',
                'com.ec',
                'org.uy',
                'ong',
                'co.cr',
                'blogspot.mx',
                'barcelona',
                'org.mx',
                'gt',
                'bo',
                'hn',
                'blogspot.com.co',
                'co',
                'net.co',
                'pe.kr',
                'crs',
                'com.sv',
                'gl',
                'blogspot.com.ar',
                'edu.ar',
                'gob.ec',
                'gob.ar',
                'com.bo',
                'madrid',
                'org.ar',
                'com.uy',
                'cr',
                'cc',
                'com.es',
                'edu.uy',
                'org.py',
                'com.co',
                'gov.ar',
                'ec',
                'gob.mx',
                'com.ar',
                'com.pe',
                'gov.co',
                'gob.ve',
                'com.mx',
                'edu.ec',
                'gov.py',
                'soy',
                'com.pa',
                'voto',
                'blogspot.com.es',
                'casa',
                'la',
                'edu.pe',
                'miami',
                'org.ve',
                'gob.do',
                'uy',
                'edu.mx',
                'ltda',
                'gob.pe',
                'blogspot.cl',
                'com.do',
                'viajes',
                'edu.co',
                'org.es',
                'villas',
                'org.pe',
                'cl',
                'do',
                'com.ve',
                'net.ar',
                'co.tz',
                'uno', 'bw', 'bi', 'cv', 'km', 'dj', 'eg', 'er', 'sz', 'et', 'gm', 'gh', 'gn', 'gw', 'ke', 'ls', 'lr', 'ly', 'mu', 'yt', 'na', 'ne', 'ng', 're', 'rw', 'sh', 'st', 'sc', 'sl', 'so', 'za', 'ss', 'sd', 'tz', 'ug', 'zm', 'zw',
                'eus', 'gal', 'com.gt'],
    'Swedish': ['sv', 'se', 'ax'],
    'Turkish': ['tr',
                'ist',
                'blogspot.com.tr',
                'av.tr',
                'gen.tr',
                'org.tr',
                'tr.gg',
                'bel.tr',
                'name.tr',
                'xn--tckwe',
                'k12.tr',
                'net.tr',
                'web.tr',
                'istanbul',
                'tur.ar',
                'tur.br',
                'gov.tr',
                'date',
                'xn--ses554g',
                'biz.tr',
                'xn--mk1bu44c',
                'com.tr',
                'xn--mgbab2bd',
                'krd'],
    'Ukrainian': ['uk',
                  'gov.ua',
                  'od.ua',
                  'dp.ua',
                  'ua',
                  'kh.ua',
                  'lviv.ua',
                  'co.ua',
                  'kiev.ua',
                  'org.ua',
                  'com.ua',
                  'in.ua',
                  'if.ua',
                  'at.ua',
                  'pp.ua',
                  'ucoz.ua',
                  'zp.ua',
                  'kharkov.ua',
                  'ho.ua', 'net.ua'],
    'Uzbek': ['uz']}

other_spisok_dom = ['scot', 'adult', 'agency', 'app', 'bank', 'bet', 'blue', 'catering', 'church', 
                    'clothing', 'community', 'consulting', 'design', 'name', 'expert', 'moda', 
                    'fashion', 'money', 'fishing', 'foundation', 'gal', 'gold', 'green', 'shiksha', 
                    'host', 'pantheonsite.io', 'avablog.ir', 'mma', 'markets', 'med', 'pub', 'school', 
                    'storage', 'tv', 'tatar', 'technology', 'tel', 'bid', 'rent', 'tennis', 
                    'partners', 'travel', 'buzz', 'courses', 'furniture', 'theater', 'tools', 
                    'tours', 'trade', 'ventures', 'cymru', 'africa', 'apartments', 'audio', 
                    'band', 'bar', 'bio', 'boo', 'business', 'ceo', 'club', 'codes', 'coffee', 'condos', 
                    'construction', 'coop', 'dance', 'deals', 'degree', 'delivery', 'dental', 'discount', 
                    'education', 'engineering', 'today', 'events', 'fail', 'fans', 'finance', 'garden', 
                    'glass', 'earth', 'health', 'hiphop', 'info', 'market', 'media', 'motorcycles', 'new', 
                    'promo', 'realestate', 'realty', 'rest', 'rsvp', 'sbs', 'science', 'sex', 'shop', 
                    'solar', 'store', 'style', 'team', 'to', 'town', 'work', 'wtf', 'xn--9dbq2a', 'xn--g2xx48c', 'yachts', 'zone']




spisok = {"Scottish": 'scot',
          "'com.cy' is a domain": 'com.cy',
          'Adult websites are typically English-language websites': 'adult',
          'Afrikaans': 'blogspot.co.za',
          'Agency is not a regional domain.': 'agency',
          'Albanian': 'al',
          'App': 'app',
          'Asian': 'asia',
          'Bangladesh': 'edu.bd',
          'Banking is a global industry, so': 'bank',
          'Basque': 'eus',
          'Bet is not a regional domain.': 'bet',
          'Blue is not a regional domain.': 'blue',
          'Bosnian': 'ba',
          'Canadian': 'mb.ca',
          'Catalan': 'ad',
          'Catering is not a regional domain': 'catering',
          'Church\n\nEnglish': 'church',
          'Clothing is not a regional domain.': 'clothing',
          'Community': 'community',
          'Consulting is not a regional domain': 'consulting',
          'Croatian': 'hr',
          'Design is not a regional domain.': 'design',
          'Domain zones can be regional or not.': 'name',
          'Expert': 'expert',
          'Faroese': 'fo',
          'Farsi': 'r98.ir',
          'Fashion': 'moda',
          'Fashion is not a regional domain.': 'fashion',
          'Filipino': 'edu.ph',
          'Finance': 'money',
          'Fishing is a regional domain.': 'fishing',
          'Foundation\n\nEnglish': 'foundation',
          'Galician.': 'gal',
          'Georgian.': 'ge',
          'Gold is not a regional domain.': 'gold',
          'Green is not a regional domain.': 'green',
          'Guatemala': 'com.gt',
          'Hebrew': 'co.il',
          'Hindi': 'shiksha',
          'Host\n\nRussian': 'host',
          'Icelandic': 'is',
          'International': 'pantheonsite.io',
          'Iran': 'avablog.ir',
          'Kurdish': 'krd',
          'Kyrgyz': 'kg',
          'MMA is not a regional domain,': 'mma',
          'Macedonia': 'mk',
          'Macedonian': 'org.mk',
          'Malay': 'blogspot.my',
          'Maldives': 'mv',
          'Markets is not a regional domain.': 'markets',
          'Mediterranean': 'med',
          'Middle East': 'co.ir',
          'Mongolian.': 'mn',
          'Nepali': 'org.np',
          'Nigeria': 'edu.ng',
          'No definitive answer.': 'vip',
          'Nu is not a regional domain.': 'nu',
          'One\n\nDomain': 'one',
          'Pakistan': 'com.pk',
          'Pakistani': 'pk',
          'Pali': 'pw',
          'Persian': 'ac.ir',
          'Pub is not a regional domain.': 'pub',
          'School\n\nEducation': 'school',
          'Serbian': 'rs',
          'Somali': 'so',
          'South Asia': 'lk',
          'Storage is not a regional domain.': 'storage',
          'TV is a domain zone, not a': 'tv',
          'Tajik.': 'tj',
          'Tatar': 'tatar',
          'Technology is not a regional domain.': 'technology',
          'Telugu': 'tel',
          'Thai': 'in.th',
          "The best match for the 'bid'": 'bid',
          "The best match for the 'rent'": 'rent',
          'The best match for the domain zone "': 'tennis',
          "The best match for the domain zone '": 'partners',
          'The best match for the regionality of': 'travel',
          "The domain 'buzz' is not": 'buzz',
          "The domain 'courses' is not": 'courses',
          'The language that best matches the regionality': 'furniture',
          'Theater is not a regional domain.': 'theater',
          'Tokelau': 'tk',
          'Tools is not a regional domain.': 'tools',
          'Tourism': 'tours',
          'Trade is not a regional domain.': 'trade',
          'Ukrainian.': 'net.ua',
          'Ventures is not a regional domain': 'ventures',
          'Vietnamese': 'vn',
          'Welsh': 'cymru',
          'africa\n\nAfrica': 'africa',
          'apartments\n\nEnglish': 'apartments',
          'audio\n\nEnglish': 'audio',
          'band\n\nEnglish': 'band',
          'bar\n\nNone of the above.': 'bar',
          'bio\n\nEnglish': 'bio',
          'boo\n\nNot regional.': 'boo',
          'business\n\nEnglish': 'business',
          'bz\n\nPortuguese': 'bz',
          'ceo\n\nSpanish': 'ceo',
          'club\n\nInternational': 'club',
          'codes\n\ninternational': 'codes',
          'coffee\n\nEnglish': 'coffee',
          'condos\n\nSpanish': 'condos',
          'construction\n\nEnglish': 'construction',
          'coop is not a regional domain.': 'coop',
          'dance\n\nEnglish': 'dance',
          'deals\n\nEnglish': 'deals',
          'degree\n\nEnglish': 'degree',
          'delivery\n\nEnglish': 'delivery',
          'dental\n\nEnglish': 'dental',
          'discount\n\nEnglish': 'discount',
          'dz\n\nDomain': 'dz',
          'education\n\nEnglish': 'education',
          'engineering\n\nEnglish': 'engineering',
          'english': 'today',
          'events\n\nEnglish': 'events',
          'fail\n\nN/A': 'fail',
          'fans\n\ninternational': 'fans',
          'finance\n\nEnglish': 'finance',
          'garden\n\nEnglish': 'garden',
          'glass\n\nEnglish': 'glass',
          'global': 'earth',
          'go.tz is a domain in Tanzania': 'go.tz',
          'health\n\nEnglish': 'health',
          'hiphop is not a regional domain.': 'hiphop',
          'info\n\nInformation': 'info',
          'marketing': 'market',
          'media\n\nN/A': 'media',
          'motorcycles\n\nEnglish': 'motorcycles',
          'new\n\nEnglish': 'new',
          'promo\n\nNo regional': 'promo',
          'realestate\n\nEnglish': 'realestate',
          'realty\n\nRussian': 'realty',
          'restaurants': 'rest',
          'rsvp is not a regional domain.': 'rsvp',
          'sbs\n\nSpanish': 'sbs',
          'science\n\nEnglish': 'science',
          'sex\n\nEnglish': 'sex',
          'sh\n\nEnglish': 'sh',
          'shop\n\nEnglish': 'shop',
          'solar\n\nEnglish': 'solar',
          'store\n\nEnglish': 'store',
          'style\n\nEnglish': 'style',
          'team\n\nEnglish': 'team',
          'to\n\nEnglish': 'to',
          'town\n\nEnglish': 'town',
          'work\n\nEnglish': 'work',
          'wtf\n\nEnglish': 'wtf',
          'xn--9dbq2a': 'xn--9dbq2a',
          'xn--g2xx48c': 'xn--g2xx48c',
          'yachts\n\nEnglish': 'yachts',
          'zone\n\nEnglish': 'zone'}


spisok2 = []
for i in spisok.values():
    spisok2.append(i)
print(spisok2)






ccTLDs = ['en', 'com', 'us', 'so', 'go.tz', 'vn', 'africa', 'net.in', 'lk', 'is', 'edu.bd', 'onlinehome.us', 'bc.ca', 
          'in', 'sydney', 'gov.za', 'durban', 'ab.ca', 'ai', 'co.ke', 'vic.edu.au', 'or.tz', 'notts.sch.uk', 
          'org.uk', 'staffs.sch.uk', 'wales', 'derbyshire.sch.uk', 'uk', 'biz', 'gc.ca', 'ky', 'org.au', 'website', 
          'carrd.co', 'blogspot.com.au', 'com.mt', 'gloucs.sch.uk', 'lancs.sch.uk', 'nyc', 'belfast.ni.sch.uk', 
          'norfolk.sch.uk', 'ac', 'suffolk.sch.uk', 'vc', 'co.bw', 'org.za', 'com.au', 'ac.in', 'co.in', 'repl.co', 
          'org', 'essex.sch.uk', 'cambs.sch.uk', 'gov.in', 'wa.edu.au', 'hants.sch.uk', 'oxon.sch.uk', 'com.gh', 'gs', 
          'co.nz', 'net.nz', 'warwickshire.sch.uk', 'ltd.uk', 'org.uk', 'co.za', 'ac.nz', 'sg', 'vg', 'govt.nz', 'bm', 
          'nic.in', 'ie', 'aero', 'worcs.sch.uk', 'org.pk', 'gov.pk', 'rw', 'com.na', 'org.ph', 'gov.au', 'herts.sch.uk', 
          'blogspot.in', 'com.ph', 'net.au', 'wilts.sch.uk', 'bw', 'bi', 'cv', 'km', 'dj', 'eg', 'er', 'sz', 'et', 'gm', 
          'gh', 'gn', 'gw', 'ke', 'ls', 'lr', 'ly', 'mw', 'mu', 'yt', 'na', 'ne', 'ng', 're', 'sh', 'st', 'sl', 'so', 
          'za', 'ss', 'sd', 'tz', 'ug', 'zm', 'zw', 'scot', 'blogspot.co.za', 'mb.ca', 'edu.ph', 'tv', 'cymru', 
          'bz', 'sh', 'to', 'ms', 'au', 'co.ug', 'tc', 'ug', 'on.ca', 'je', 'co.zw', 'sg', 'as', 'mt', 'gov', 'im', 
          'org.sg', 'lincs.sch.uk', 'surrey.sch.uk', 'edu.in', 'gov.au', 'blogspot.ca', 'ca', 'liverpool.sch.uk', 
          'devon.sch.uk', 'ws', 'blogspot.ie', 'org.nz', 'leeds.sch.uk', 'somerset.sch.uk', 'edu.au', 'edu.sg', 'github.io', 
          'org.pk', 'gov.pk', 'readthedocs.io', 'gitlab.io', 'n-yorks.sch.uk', 'gov.au', 'blogspot.in', 'com.ph', 'net.au', 
          'wilts.sch.uk', 'glitch.me', 'bham.sch.uk','ghost.io','leics.sch.uk','northumberland.sch.uk','cumbria.sch.uk', 'blogspot.sg','durham.sch.uk','com.sg', 'com.gh', 'net.nz','co.nz','warwickshire.sch.uk', 'vg','govt.nz', 'bm', 
'me.uk', 'nic.in', 'lpages.co', 'nz', 'asn.au', 'cornwall.sch.uk', 'now.sh', 'com.na', 'cam', 'school.nz', 'rw', 'boston', 'kent.sch.uk', 'neustar', 'republican','glasgow.sch.uk','org.ph', 'herts.sch.uk', 
'capetown', 'bw', 'bi', 'cv', 'km', 'dj', 'eg', 'er', 'sz', 'et', 'gm', 'gh', 'gn', 'gw', 'sh', 'st', 'sl', 'ss', 'sd', 'zw', 'mb.ca', 'edu.ph', 'pantheonsite.io']

gTLDs = ['sale', 'physio', 'shiksha', 'restaurant', 'top', 'eco', 'organic', 'security', 'pet', 'pictures', 
         'world', 'systems', 'fitness', 'yoga', 'blackfriday', 'loans', 'press', 'property', 'software', 'basketball', 
         'creditunion', 'sydney', 'singles', 'mom', 'soccer', 'diamonds', 'airforce', 'studio', 'university', 'vacations', 
         'estate', 'watch', 'build', 'broadway', 'hockey', 'coach', 'beauty', 'tips', 
         'care', 'red', 'reviews', 'how', 'rip', 'training', 'gripe', 'recipes', 'repair', 'porn', 'video', 'actor', 'horse', 
         'plus', 'pharmacy', 'supplies', 'tube', 'jewelry', 'exposed', 'camera', 'investments', 'llc', 'loan', 'kids', 'auction', 
         'guru', 'show', 'surgery', 'properties', 'page', 'rugby', 'hair', 'tax', 'farm', 'party', 'tattoo', 'xxx', 'movie', 'insure', 
         'shoes', 'cloud', 'hosting', 'feedback', 'holdings', 'tickets', 'limo',  
         'poker', 'voyage', 'gives', 'limited', 'wedding', 'enterprises', 'army', 'online', 
         'country', 'racing', 'direct', 'kitchen', 'energy', 'contractors', 'site', 'radio', 'graphics', 'marketing', 
         'flowers', 'creditcard', 'broker', 'makeup', 'webcam', 'chat', 'qpon', 'bike', 'cash', 'management', 
         'vet', 'cooking', 'cpa', 'engineer', 'gallery', 'company', 'mba', 'rehab', 'dentist', 'florist', 'equipment', 
         'democrat', 'forex', 'institute', 'coupons', 'healthcare', 'ink', 'baby', 'golf', 'bible', 
         'bargains', 'cruises', 'museum', 'bingo', 'supply', 'day', 'doctor', 'vegas', 'live', 'vote', 'game', 'wiki', 
         'forsale', 'contact', 'exchange', 'ski', 'cool', 'land', 'help', 'autos', 'casino', 'hospital', 'ltd', 
         'tech', 'accountant', 'house', 'click', 'law', 'fm', 'associates', 'blog', 'games', 'domains', 'kiwi', 
         'lighting', 'place', 'builders', 'space', 'irish', 'solutions', 'photography', 'attorney', 'men', 
         'review', 'film', 'financial', 'select', 'aero', 'camp', 'worcs.sch.uk', 'xyz', 'link', 'faith', 
         'io', 'lawyer', 'plumbing', 'careers', 'cleaning', 'cricket', 'download', 
         'pro', 'whoswho', 'academy', 'fish', 'realtor', 'sucks', 'report', 'mobi', 'social', 'group', 'city', 'computer', 
         'international', 'clinic', 'lgbt', 'claims', 'diet', 'guide', 'credit', 'industries', 'rocks', 
         'charity', 'photos', 'melbourne', 'email', 'dog', 'shopping', 'flights', 'stream', 'pics', 'legal', 'life', 
         'rodeo', 'fyi', 'career', 'gifts', 'boats', 'cards', 'best', 'onl',  
         'net', 'love', 'family', 'global', 'dev', 'college', 'sexy', 'observer', 'skin', 'trading', 'parts', 
         'tires', 'win', 'works', 'giving', 'black', 'icu', 'mortgage', 'fit', 'toys', 'gay', 'network', 'study', 'navy', 
         'lease', 'sport', 'accountants', 'synology.me', 'compare', 'cheap', 'quest', 'lol', 'menu',  
         'guitars', 'news', 'monster', 'directory', 'scot', 'tv', 'cymru', 
        ]
org

vars3 = []
