websites = {
    # "https://www.blogger.com/": [
    #     {"r_knopkа_Sozdat_Blog_and_click": """my_wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="maincontent"]/section[1]/header/a'))).click()"""},
    #     {"r_google_autorization": """my_wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="view_container"]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div/div/ul/li[1]/div/div[1]/div/div[2]/div[2]')))"""},
    #     {"r_google_authorization_function": "gmail_autoriz_fun(driver, email, password)"},
    #     {"r_reg_ozidaem_zagruzku_site": """my_wait.until(EC.url_contains("blogger.com"))"""},
    #     {"r_reg_nazva_bloga_find": """reg_nazva = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div[1]/span/div[2]/div/div/div[1]/div/div[1]/input')"""},
    #     {"r_reg_nazva_bloga_input": """reg_nazva.send_keys("The dog house game my blog")"""},
    #     {"r_reg_nazva_bloga_click_next": """driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div[1]/span/div[3]/div[2]/div/div[2]/div[2]/span/span').click()"""},
    #     {"r_reg_url_bloga_wait": "time.sleep(1)"},
    #     {"r_reg_url_bloga_find_input": """reg_url = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div[1]/span/div[2]/div/div/div[1]/div/div[1]/input')"""},
    #     {"r_reg_url_bloga_input": """reg_url.send_keys("the-dog-house23")"""},
    #     {"r_reg_url_bloga_click_next": """driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div[1]/span/div[3]/div[2]/div/div[2]/div[2]/span/span').click()"""},
    #     {"r_author_name_wait": "time.sleep(1)"},
    #     {"r_author_name_input": """author_name = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div[1]/span/div[2]/div/div/div[1]/div/div[1]/input')"""},
    #     {"r_author_name_click_next": """author_name.send_keys("Alexandr Riddic")"""},
    #     {"new_post_wait_and_click": """my_wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="gb"]/div[4]/div[2]/div/c-wiz/div[2]/div/div/span/span/span[2]'))).click()"""},
    #     {"post_write_title": """post_nazva = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz[2]/div/c-wiz/div/div[1]/div[1]/div[1]/div/div[1]/input')"""},
    #     {"post_write_title": """post_nazva.send_keys("My Post About - The dog house game my blog 2")"""},
    #     {"knopka_in_HTML_code": """html_knopka = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz[2]/div/c-wiz/div/div[2]/div/div/div[3]/span/div/div[2]/div[1]/div[1]/div[1]')"""},
    #     {"knopka_in_HTML_code_action": "ActionChains(driver).move_to_element(html_knopka).click().perform()"},
    #     {"knopka_in_HTML_code_2": """html_knopka2 = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz[2]/div/c-wiz/div/div[2]/div/div/div[3]/span/div/div[2]/div[1]/div[1]/div[1]/div/div[2]/div[1]')"""},
    #     {"knopka_in_HTML_code_action_2": "ActionChains(driver).move_to_element(html_knopka2).click().perform()"},
    #     {"post_write_text_find_block": """post_text = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz[2]/div/c-wiz/div/div[2]/div/div/div[3]/span/div/div[2]/div[2]/div/div/div/div[6]')"""},
    #     {"post_write_text_click_block": "ActionChains(driver).move_to_element(post_text).click().perform()"},
    #     {"post_write_text": """post_text.send_keys("My_Tedxt*******************")"""},
    #     {"link_post_click": """driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div/div[2]/div/div/div[4]/span/c-wiz/div/div[2]/div[3]/div/span/div/div').click()"""},
    #     {"link_post_text": """link_post_text = driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div/div[2]/div/div/div[4]/span/c-wiz/div/div[2]/div[3]/span/div[1]/span').text"""},
    #     {"print_link": "print(link_post_text)"},
    #     {"click_publish_1": """driver.find_element(By.XPATH, '/html/body/div[7]/c-wiz/div/c-wiz/div/div[1]/div[2]/div[4]/span').click()"""},
    #     {"click_publish_2": """my_wait.until(EC.presence_of_element_located((By.XPATH, '/html/body/div[7]/div[4]/div/div[2]/div[3]/div[2]'))).click()"""},
    #     {"time_wait_2": "time.sleep(2)"},
    # ],

    # "https://blogs.cornell.edu/advancedrevenuemanagement12/2012/03/28/revenue-management-in-the-golf-industry/": [
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="comment"]').send_keys(my_new_comment)"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="author"]').send_keys(my_author)"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email])"""},
    #     {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wp-comment-cookies-consent"]').click()"""},
    #     {"captcha_img_1": """captcha_img_XPATH = '//*[@id="secureimg"]'"""},                                            # XPATH images
    #     {"captcha_img_2": """captcha_img_XPATH_text = fun_my_captcha_image(driver, captcha_img_XPATH)"""},
    #     {"captcha_img_3": """captcha_find_input_text = driver.find_element(By.XPATH, '//*[@id="securitycode"]')"""},    # XPATH поле ввода
    #     {"captcha_img_4": """ActionChains(driver).move_to_element(captcha_find_input_text).click().perform()"""},
    #     {"captcha_img_5": """captcha_find_input_text.send_keys(captcha_img_XPATH_text)"""},
    #     {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    #     ],
    # "https://blogs.cornell.edu/advancedrevenuemanagement12/2012/03/28/casino-revenue-management/": [
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="comment"]').send_keys(my_new_comment)"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="author"]').send_keys(my_author)"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email])"""},
    #     {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wp-comment-cookies-consent"]').click()"""},
    #     {"captcha_img_1": """captcha_img_XPATH = '//*[@id="secureimg"]'"""},                                            # XPATH images
    #     {"captcha_img_2": """captcha_img_XPATH_text = fun_my_captcha_image(driver, captcha_img_XPATH)"""},
    #     {"captcha_img_3": """captcha_find_input_text = driver.find_element(By.XPATH, '//*[@id="securitycode"]')"""},    # XPATH поле ввода
    #     {"captcha_img_4": """ActionChains(driver).move_to_element(captcha_find_input_text).click().perform()"""},
    #     {"captcha_img_5": """captcha_find_input_text.send_keys(captcha_img_XPATH_text)"""},
    #     {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    #     ],
    # "https://blogs.cornell.edu/advancedrevenuemanagement12/2012/03/26/railway-industry-in-france/": [
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="comment"]').send_keys(my_new_comment)"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="author"]').send_keys(my_author)"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email])"""},
    #     {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wp-comment-cookies-consent"]').click()"""},
    #     {"captcha_img_1": """captcha_img_XPATH = '//*[@id="secureimg"]'"""},                                            # XPATH images
    #     {"captcha_img_2": """captcha_img_XPATH_text = fun_my_captcha_image(driver, captcha_img_XPATH)"""},
    #     {"captcha_img_3": """captcha_find_input_text = driver.find_element(By.XPATH, '//*[@id="securitycode"]')"""},    # XPATH поле ввода
    #     {"captcha_img_4": """ActionChains(driver).move_to_element(captcha_find_input_text).click().perform()"""},
    #     {"captcha_img_5": """captcha_find_input_text.send_keys(captcha_img_XPATH_text)"""},
    #     {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    #     ],
    # "https://www.paleorunningmomma.com/paleo-homemade-oreos-grain-free-dairy-free/": [
    #     {"a1": """a1 = driver.find_element(By.XPATH, '//*[@id="comment"]').click()"""},
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="comment"]').send_keys(my_new_comment)"""},
    #     {"a3": """a3 = driver.find_element(By.XPATH, '//*[@id="author"]').click()"""},
    #     {"a4": """a4 = driver.find_element(By.XPATH, '//*[@id="author"]').send_keys(my_author)"""},
    #     {"a5": """a5 = driver.find_element(By.XPATH, '//*[@id="email"]').click()"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email)"""},
    #     {"a7": """a7 = driver.find_element(By.XPATH, '//*[@id="url"]').click()"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="url"]').send_keys(my_site_backlink)"""},
    #     {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wp-comment-cookies-consent"]').click()"""},
    #     {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    #     ],

    # "https://www.paleorunningmomma.com/loaded-taco-sweet-potato-sliders-paleo-whole30/": 
    # [
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="comment"]').send_keys(my_new_comment)"""},
    #     {"a4": """a4 = driver.find_element(By.XPATH, '//*[@id="author"]').send_keys(my_author)"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email)"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="url"]').send_keys(my_site_backlink)"""},
    #     {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wp-comment-cookies-consent"]').click()"""},
    #     {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    # ],
    # "http://www.kosmetichka.ru/kosmoforum/ucp.php?mode=register": [
    # {"a3": """a3 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]').send_keys(my_author)"""},
    # {"a5": """a5 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[4]/td[2]/input[1]').send_keys(my_email)"""},
    # {"a7": """a7 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[5]/td[2]/input[1]').send_keys(my_email)"""},
    # {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[6]/td[2]/input[1]').click()"""},
    # {"a9": """a9 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[6]/td[2]/input[1]').send_keys('pass')"""},
    # {"a10": """a10 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[7]/td[2]/input[1]').click()"""},
    # {"a11": """a11 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[7]/td[2]/input[1]').send_keys('pass')"""},
    # {"a12": """a12 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[11]/td[2]/input[1]').click()"""},
    # {"a13": """a13 = driver.find_element(By.XPATH, '//*[@id="wrapcentre"]/form[1]/table[1]/tbody[1]/tr[11]/td[2]/input[1]').send_keys('Пять')"""},
    # {"a15": """a15 = driver.find_element(By.XPATH, '//*[@id="submit"]').click()"""},
    # ],
    # "https://bdfeu.ukraine7.com/register": [
    #     {"a1": """a1 = driver.find_element(By.XPATH, '//*[@id="username_reg"]').click()"""},
    #     {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="username_reg"]').send_keys('Author Sasha')"""},
    #     {"a3": """a3 = driver.find_element(By.XPATH, '//*[@id="email"]').click()"""},
    #     {"a4": """a4 = driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(my_email)"""},
    #     {"a5": """a5 = driver.find_element(By.XPATH, '//*[@id="password_reg"]').click()"""},
    #     {"a6": """a6 = driver.find_element(By.XPATH, '//*[@id="password_reg"]').send_keys('1232333')"""},
    #     {"a7": """a7 = driver.find_element(By.XPATH, '//*[@id="wantsnews"]').click()"""},
    #     {"a8": """a8 = driver.find_element(By.XPATH, '//*[@id="ucp"]/fieldset[1]/input[1]').click()"""},
    #     ],
    "https://www.lesmaquettistes.com/login": [
        {"topic_it": """driver.find_element(By.XPATH, '//*[@id="topicit-connect-0"]').click()"""},
        {"knopka_in_HTML_code_action_2": "ActionChains(driver).move_to_element(a1).click().perform()"},
        {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="form-login"]/div[1]/input[1]').send_keys('sdfsd@fgfdg')"""},
        {"a3": """a3 = driver.find_element(By.XPATH, '//*[@id="form-login"]').click()"""},
        {"a4": """a4 = driver.find_element(By.XPATH, '//*[@id="form-login"]/div[2]/input[1]').send_keys('xxcvxcvxcvxv')"""},
        ],
    "https://bdfeu.ukraine7.com/login": [
        {"topic_it": """driver.find_element(By.XPATH, '//*[@id="topicit-connect-0"]').click()"""},
        {"knopka_in_HTML_code_action_2": "ActionChains(driver).move_to_element(a1).click().perform()"},
        {"a2": """a2 = driver.find_element(By.XPATH, '//*[@id="form-login"]/div[1]/input[1]').send_keys('sdfsd@fgfdg')"""},
        {"a3": """a3 = driver.find_element(By.XPATH, '//*[@id="form-login"]').click()"""},
        {"a4": """a4 = driver.find_element(By.XPATH, '//*[@id="form-login"]/div[2]/input[1]').send_keys('xxcvxcvxcvxv')"""},
        ],
   
}